# Generated by Django 5.2.3 on 2025-12-16 06:12

import public_folder.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=public_folder.models.public_upload_path)),
                ('provided_name', models.CharField(blank=True, help_text='Optional filename entered by uploader', max_length=255)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
