# Generated by Django 5.2.3 on 2025-11-19 09:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('credential_type', models.CharField(choices=[('priority 1', 'Priority 1'), ('priority 2', 'Priority 2')], default='priority 1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('firm_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone1', models.CharField(max_length=15)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.businesstype')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('started', 'Started'), ('finish', 'Finish'), ('in_progress', 'In Progress')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('reputed_person_name', models.CharField(blank=True, max_length=100)),
                ('reputed_person_number', models.CharField(blank=True, max_length=15)),
                ('software', models.CharField(max_length=100)),
                ('nature', models.CharField(blank=True, choices=[('', 'Select'), ('supermarket', 'Supermarket'), ('textile', 'Textile'), ('restaurant', 'Restaurant'), ('Agency/Distribution', 'Agency/Distribution'), ('retail', 'Retail'), ('Auto Mobiles', 'Auto Mobiles'), ('Bakery', 'Bakery'), ('Boutique', 'Boutique'), ('Hyper Market', 'Hyper Market'), ('Lab', 'Lab')], max_length=50)),
                ('no_of_system', models.IntegerField()),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('installation_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('software_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('module_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('more_modules', models.TextField(blank=True, null=True)),
                ('modules', models.TextField(blank=True)),
                ('module_prices', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('key_uploaded', 'Key Uploaded'), ('rejected', 'Rejected'), ('under_process', 'Under Process')], default='pending', max_length=20)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.branch')),
            ],
        ),
        migrations.CreateModel(
            name='CredentialDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app2.credentials')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.field')),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Separate each point with a new line')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.department')),
            ],
        ),
        migrations.CreateModel(
            name='JobRoleDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='app2.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='InformationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('remark', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('thumbnail', models.ImageField(upload_to='information_thumbnails/')),
                ('priority', models.CharField(choices=[('priority1', 'Priority 1'), ('priority2', 'Priority 2')], max_length=20)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField(default=1)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.productcategory')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('deadline', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'), ('hold', 'On Hold')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ManyToManyField(related_name='project_assignments', to='app1.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.socialmediaproject')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.task')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'), ('hold', 'On Hold')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='app2.socialmediaprojectassignment')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='StandbyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('with_customer', 'With Customer')], default='in_stock', help_text='Current status of the item', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_place', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Standby Item',
                'verbose_name_plural': 'Standby Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StandbyReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('return_notes', models.TextField(blank=True, null=True)),
                ('stock_on_return', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name_at_return', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_place_at_return', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone_at_return', models.CharField(blank=True, max_length=15, null=True)),
                ('issued_date_at_return', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='app2.standbyitem')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StandbyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='standby_images/')),
                ('image_type', models.CharField(choices=[('original', 'Original'), ('return_condition', 'Return Condition'), ('other', 'Other')], default='original', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app2.standbyitem')),
                ('standby_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_images', to='app2.standbyreturn')),
            ],
        ),
    ]
