# Generated by Django 5.0.2 on 2025-05-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
