# Generated by Django 5.0.2 on 2025-05-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credentials',
        ),
    ]
