# Generated by Django 5.2.4 on 2026-02-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='status',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('review', 'Review/Testing'), ('completed', 'Completed'), ('hold', 'Hold')], default='in_progress', max_length=50),
        ),
    ]
