# Generated by Django 5.2.7 on 2026-03-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
