# Generated by Django 5.2.4 on 2026-02-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_alter_dailytask_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailytask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Daily Task', 'verbose_name_plural': 'Daily Tasks'},
        ),
        migrations.AddField(
            model_name='dailytask',
            name='elapsed_seconds',
            field=models.IntegerField(default=0, help_text='Total elapsed time in seconds'),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='is_timer_running',
            field=models.BooleanField(default=False, help_text='Is the timer currently running'),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='last_started_at',
            field=models.DateTimeField(blank=True, help_text='When task was last started/resumed', null=True),
        ),
    ]
