# Generated by Django 5.2.7 on 2026-04-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_feeder_created_by'),
        ('app2', '0003_alter_dailytask_options_dailytask_elapsed_seconds_and_more'),
    ]

    operations = [
    ]
