# Generated by Django 5.0.2 on 2025-05-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
