# Generated by Django 5.0.2 on 2025-05-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_credentialdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
