# Generated by Django 5.0.2 on 2025-05-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='credential_type',
            field=models.CharField(choices=[('priority 1', 'Priority 1'), ('priority 2', 'Priority 2')], default='priority 1', max_length=50),
        ),
    ]
