# Generated by Django 5.0.2 on 2025-05-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_credentials_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='added_by',
        ),
    ]
