# Generated by Django 5.0.2 on 2025-05-15 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0151_project_deadline'),
        ('app2', '0010_remove_credentials_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_credentials', to='app1.user'),
        ),
    ]
