# Generated by Django 5.0.2 on 2025-05-16 05:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0014_remove_credentials_added_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='InformationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('remark', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('thumbnail', models.ImageField(upload_to='information_thumbnails/')),
                ('priority', models.CharField(choices=[('priority1', 'Priority 1'), ('priority2', 'Priority 2')], max_length=20)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.productcategory')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.producttype')),
            ],
        ),
    ]
