# Generated by Django 5.0.2 on 2025-05-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0015_producttype_productcategory_informationcenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='product_type',
        ),
    ]
