# Generated by Django 5.0.2 on 2025-05-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0017_dailytask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='duration',
            field=models.CharField(max_length=50),
        ),
    ]
