# Generated by Django 5.0.2 on 2025-05-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0018_alter_dailytask_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
