# Generated by Django 5.0.2 on 2025-05-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0019_dailytask_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationcenter',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='informationcenter',
            name='host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='informationcenter',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
