# Generated by Django 5.0.2 on 2025-06-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0020_informationcenter_duration_informationcenter_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('started', 'Started'), ('finish', 'Finish'), ('in_progress', 'In Progress')], default='in_progress', max_length=20),
        ),
    ]
