# Generated by Django 5.0.2 on 2025-06-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0021_alter_dailytask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationcenter',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
