# Generated by Django 5.0.2 on 2025-06-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0022_informationcenter_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
