# Generated by Django 5.0.2 on 2025-06-19 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0024_jobrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRoleSubHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Separate each point with a new line')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_headings', to='app2.jobrole')),
            ],
        ),
    ]
