# Generated by Django 5.0.2 on 2025-06-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0025_jobrolesubheading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobRoleSubHeading',
        ),
    ]
