# Generated by Django 5.0.2 on 2025-06-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0026_delete_jobrolesubheading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrole',
            name='description',
        ),
        migrations.AddField(
            model_name='jobrole',
            name='descriptions',
            field=models.JSONField(default=list),
        ),
    ]
