# Generated by Django 5.0.2 on 2025-06-20 04:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0027_remove_jobrole_description_jobrole_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrole',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='jobrole',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, help_text='Separate each point with a new line'),
            preserve_default=False,
        ),
    ]
