# Generated by Django 5.0.2 on 2025-06-20 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0028_remove_jobrole_descriptions_jobrole_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRoleDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='app2.jobrole')),
            ],
        ),
    ]
