# Generated by Django 5.0.2 on 2025-07-07 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0032_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
    ]
