# Generated by Django 5.0.2 on 2025-07-08 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0187_complaintimage'),
        ('app2', '0033_remove_task_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.ManyToManyField(related_name='assigned_projects', to='app1.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.socialmediaproject')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.task')),
            ],
        ),
    ]
