# Generated by Django 5.0.2 on 2025-07-08 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0187_complaintimage'),
        ('app2', '0034_socialmediaprojectassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaprojectassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmediaprojectassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='socialmediaprojectassignment',
            name='assigned_to',
            field=models.ManyToManyField(related_name='project_assignments', to='app1.user'),
        ),
    ]
