# Generated by Django 5.0.2 on 2025-07-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0035_socialmediaprojectassignment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaprojectassignment',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
