# Generated by Django 5.0.2 on 2025-07-10 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0037_socialmediaprojectassignment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaprojectassignment',
            name='status',
        ),
    ]
