# Generated by Django 5.0.2 on 2025-07-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0039_socialmediaprojectassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaprojectassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaprojectassignment',
            name='hold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaprojectassignment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
