# Generated by Django 5.0.2 on 2025-07-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0040_socialmediaprojectassignment_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaprojectassignment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='socialmediaprojectassignment',
            name='hold_at',
        ),
        migrations.RemoveField(
            model_name='socialmediaprojectassignment',
            name='started_at',
        ),
    ]
