# Generated by Django 5.0.2 on 2025-07-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0042_assignmentstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
