# Generated by Django 5.0.2 on 2025-07-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0043_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaprojectassignment',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
