# Generated by Django 5.0.2 on 2025-07-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0045_feeder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialdetail',
            name='value',
            field=models.TextField(),
        ),
    ]
