# Generated by Django 5.0.2 on 2025-07-22 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0047_feeder_module_prices_feeder_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feeder',
        ),
    ]
