# Generated by Django 5.0.2 on 2025-07-22 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0187_complaintimage'),
        ('app2', '0048_delete_feeder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('reputed_person_name', models.CharField(blank=True, max_length=100)),
                ('reputed_person_number', models.CharField(blank=True, max_length=15)),
                ('software', models.CharField(max_length=100)),
                ('no_of_system', models.IntegerField()),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('installation_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('software_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('module_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('more_modules', models.TextField(blank=True, null=True)),
                ('modules', models.TextField(blank=True)),
                ('module_prices', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('under_process', 'Under Process')], default='pending', max_length=20)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.branch')),
                ('nature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.businesstype')),
            ],
        ),
    ]
