# Generated by Django 5.0.2 on 2025-08-01 04:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0051_alter_standbyitem_options_standbyitem_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='nature',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('supermarket', 'Supermarket'), ('textile', 'Textile'), ('restaurant', 'Restaurant'), ('Agency/Distribution', 'Agency/Distribution'), ('retail', 'Retail'), ('Auto Mobiles', 'Auto Mobiles'), ('Bakery', 'Bakery'), ('Boutique', 'Boutique'), ('Hyper Market', 'Hyper Market'), ('Lab', 'Lab')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feeder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('key_uploaded', 'Key Uploaded'), ('rejected', 'Rejected'), ('under_process', 'Under Process')], default='pending', max_length=20),
        ),
    ]
