# Generated by Django 5.2.5 on 2025-09-26 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0052_alter_feeder_nature_alter_feeder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standbyitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Standby Item', 'verbose_name_plural': 'Standby Items'},
        ),
        migrations.AddField(
            model_name='standbyitem',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('with_customer', 'With Customer')], default='in_stock', help_text='Current status of the item', max_length=20),
        ),
        migrations.AddField(
            model_name='standbyitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='standbyitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='standbyitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='standbyitem',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='standbyitem',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
