# Generated by Django 5.2.5 on 2025-10-07 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0053_alter_standbyitem_options_standbyitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standbyitem',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='standbyitem',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='standbyitem',
            name='customer_place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='standbyitem',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StandbyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='standby_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app2.standbyitem')),
            ],
        ),
        migrations.DeleteModel(
            name='StandbyItemImage',
        ),
    ]
