# Generated by Django 5.2.5 on 2025-10-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0054_standbyitem_customer_name_standbyitem_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standbyimage',
            name='image_type',
            field=models.CharField(choices=[('original', 'Original'), ('return_condition', 'Return Condition'), ('other', 'Other')], default='original', max_length=20),
        ),
    ]
