# Generated by Django 5.2.5 on 2025-10-09 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0055_standbyimage_image_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandbyReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('return_notes', models.TextField(blank=True, null=True)),
                ('stock_on_return', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name_at_return', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_place_at_return', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone_at_return', models.CharField(blank=True, max_length=15, null=True)),
                ('issued_date_at_return', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='app2.standbyitem')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='standbyimage',
            name='standby_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_images', to='app2.standbyreturn'),
        ),
    ]
