# Generated by Django 5.2.8 on 2025-11-26 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriveFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='my_drive.drivefolder')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('share_code', models.CharField(blank=True, max_length=4, null=True)),
                ('share_expiry', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='my_drive.drivefolder')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='drivefolder',
            index=models.Index(fields=['parent'], name='my_drive_dr_parent__7a4349_idx'),
        ),
        migrations.AddIndex(
            model_name='drivefolder',
            index=models.Index(fields=['created_at'], name='my_drive_dr_created_4b64f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='drivefolder',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='uniq_folder_name_per_parent'),
        ),
        migrations.AddIndex(
            model_name='drivefile',
            index=models.Index(fields=['uploaded_at'], name='my_drive_dr_uploade_53dfae_idx'),
        ),
        migrations.AddIndex(
            model_name='drivefile',
            index=models.Index(fields=['folder'], name='my_drive_dr_folder__6c62da_idx'),
        ),
    ]
