# Generated by Django 4.2.7 on 2025-11-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_drive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefile',
            name='share_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='drivefile',
            name='share_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
