# Generated by Django 5.2.4 on 2025-10-08 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_drive', '0002_drivefolder_delete_drivefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivefolder',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterField(
            model_name='drivefolder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='my_drive.drivefolder')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
