# Generated by Django 5.2.4 on 2025-10-08 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_drive', '0003_alter_drivefolder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='my_drive.drivefolder'),
        ),
        migrations.AlterField(
            model_name='drivefolder',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
