# Generated by Django 5.2.4 on 2025-10-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_drive', '0004_drivefolder_parent_alter_drivefolder_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='drivefile',
            index=models.Index(fields=['uploaded_at'], name='my_drive_dr_uploade_53dfae_idx'),
        ),
        migrations.AddIndex(
            model_name='drivefile',
            index=models.Index(fields=['folder'], name='my_drive_dr_folder__6c62da_idx'),
        ),
        migrations.AddIndex(
            model_name='drivefolder',
            index=models.Index(fields=['parent'], name='my_drive_dr_parent__7a4349_idx'),
        ),
        migrations.AddIndex(
            model_name='drivefolder',
            index=models.Index(fields=['created_at'], name='my_drive_dr_created_4b64f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='drivefolder',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='uniq_folder_name_per_parent'),
        ),
    ]
