# Generated by Django 5.2.4 on 2025-10-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_drive', '0005_drivefile_my_drive_dr_uploade_53dfae_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='drivefile',
            name='my_drive_dr_uploade_53dfae_idx',
        ),
        migrations.RemoveIndex(
            model_name='drivefile',
            name='my_drive_dr_folder__6c62da_idx',
        ),
        migrations.RemoveIndex(
            model_name='drivefolder',
            name='my_drive_dr_parent__7a4349_idx',
        ),
        migrations.RemoveIndex(
            model_name='drivefolder',
            name='my_drive_dr_created_4b64f1_idx',
        ),
    ]
