# Generated by Django 5.2.7 on 2026-06-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_form_enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
