# Generated by Django 5.2.7 on 2026-06-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_form_enquiry', '0002_enquiry_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
