# Generated by Django 5.2.7 on 2026-06-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_form_enquiry', '0003_enquiry_latitude_enquiry_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
