# Generated by Django 5.2.7 on 2026-06-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_form_enquiry', '0004_alter_enquiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
