# Generated by Django 5.2.7 on 2026-06-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_form_enquiry', '0005_enquiry_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='enquiry/audio/'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='enquiry/images/'),
        ),
    ]
