# Generated by Django 5.2.5 on 2025-10-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField()),
                ('places', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('mobile_no', models.CharField(max_length=15)),
                ('alternate_number', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
