# Generated by Django 5.2.3 on 2025-11-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sales price from Item Master MRP', max_digits=12, verbose_name='Sales Price (MRP)'),
        ),
    ]
