# Generated by Django 5.0.14 on 2025-12-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes or remarks about this item', verbose_name='Notes'),
        ),
    ]
