# Generated by Django 5.2.5 on 2025-11-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='department_logos/', verbose_name='Department Logo'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sales price from Item Master MRP', max_digits=12, verbose_name='Sales Price (MRP)'),
        ),
    ]
