# Generated by Django 5.2.5 on 2025-11-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_department_logo_purchaseorderitem_sales_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='item_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Item Cost (Entry Total ÷ Qty)'),
        ),
    ]
