# Generated by Django 5.2.5 on 2025-11-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='section',
            field=models.CharField(choices=[('GENERAL', 'General'), ('HARDWARE', 'Hardware Items'), ('SOFTWARE', 'Software Items'), ('PAPER_ROLLS', 'Paper Rolls')], default='GENERAL', help_text='Item category section', max_length=20, verbose_name='Section'),
        ),
    ]
