# Generated by Django 5.2.5 on 2025-10-13 10:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_item_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cost Price'),
        ),
        migrations.AddField(
            model_name='item',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Maximum Retail Price'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Purchase Price'),
        ),
        migrations.AddField(
            model_name='item',
            name='tax_percentage',
            field=models.DecimalField(choices=[(Decimal('5.00'), '5%'), (Decimal('18.00'), '18%'), (Decimal('28.00'), '28%')], decimal_places=2, default=Decimal('18.00'), max_digits=5, verbose_name='Tax Percentage'),
        ),
        migrations.AlterField(
            model_name='item',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='HSN Code'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
