# Generated by Django 5.2.5 on 2025-11-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_purchaseorderitem_item_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='pdf_format',
            field=models.CharField(choices=[('FORMAT_1', 'Form 1 - Standard (No Client Details)'), ('FORMAT_2', 'Form 2 - With Client Details in Items')], default='FORMAT_1', help_text='Format 1: Standard PO | Format 2: Include client details in item rows', max_length=20, verbose_name='PDF Format'),
        ),
    ]
