# Generated by Django 5.2.5 on 2025-11-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_purchaseorder_pdf_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='section',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SERVICE', 'Service Items'), ('SOFTWARE', 'Softwares')], default='GENERAL', help_text='Item category section', max_length=20, verbose_name='Section'),
        ),
    ]
