# Generated by Django 5.2.5 on 2025-10-16 14:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0005_department_purchaseorderitem_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AddField(
            model_name='department',
            name='address',
            field=models.TextField(default='Not Provided', verbose_name='Department Address'),
        ),
        migrations.AddField(
            model_name='department',
            name='alternate_number',
            field=models.CharField(blank=True, default='Not Provided', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Alternate Number'),
        ),
        migrations.AddField(
            model_name='department',
            name='city',
            field=models.CharField(default='Not Provided', max_length=60, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='department',
            name='contact_number',
            field=models.CharField(default='Not Provided', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, default='Not Provided', max_length=100, verbose_name='Email ID'),
        ),
        migrations.AddField(
            model_name='department',
            name='gst_number',
            field=models.CharField(blank=True, default='Not Provided', help_text='15-character GST Number', max_length=15, verbose_name='GST Number'),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='department',
            name='pincode',
            field=models.CharField(default='Not Provided', max_length=20, verbose_name='Pincode'),
        ),
        migrations.AddField(
            model_name='department',
            name='state',
            field=models.CharField(default='Not Provided', max_length=60, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department making the purchase', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchase_order.department', verbose_name='Buyer Department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Department Name'),
        ),
    ]
