# Generated by Django 5.2.5 on 2025-11-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_purchaseorderitem_sales_price'),
        ('purchase_order', '0005_item_section'),
    ]

    operations = [
    ]
