# Generated by Django 5.2.3 on 2025-11-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_purchaseorderitem_sales_price'),
        ('purchase_order', '0005_item_section'),
    ]

    operations = [
    ]
