# Generated by Django 5.2.5 on 2025-11-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0006_merge_20251112_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='section',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SERVICE', 'Service Items'), ('SOFTWARE', 'Softwares'), ('PAPER_ROLLS', 'Paper Rolls')], default='GENERAL', help_text='Item category section', max_length=20, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='pdf_format',
            field=models.CharField(choices=[('FORMAT_1', 'Form 1 - Standard (No Client Details)'), ('FORMAT_2', 'Form 2 - With Client Details in Items')], default='FORMAT_1', help_text='Form 1: Standard | Form 2: Includes client details', max_length=20, verbose_name='PDF Format'),
        ),
    ]
