# Generated by Django 5.2.5 on 2025-10-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0006_alter_department_options_department_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='client_details',
            field=models.TextField(default='', verbose_name='Client Details'),
        ),
    ]
