# Generated by Django 5.2.5 on 2025-10-21 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0007_remove_purchaseorder_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this item belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='purchase_order.department', verbose_name='Department'),
        ),
    ]
