# Generated by Django 5.2.3 on 2025-11-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0007_add_department_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='department_logos/', verbose_name='Department Logo'),
        ),
    ]
