# Generated by Django 5.2.5 on 2025-10-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0008_item_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approval Date'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='admin_approved_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='admin_rejection_reason',
            field=models.TextField(blank=True, verbose_name='Rejection Reason'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='admin_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Administrative approval status for this purchase order', max_length=20, verbose_name='Admin Approval Status'),
        ),
    ]
