# Generated by Django 5.2.5 on 2025-11-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0008_alter_purchaseorder_pdf_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Remarks'),
        ),
    ]
