# Generated by Django 5.2.5 on 2025-11-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0009_purchaseorderitem_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Margin (Sales Price - Item Cost)'),
        ),
    ]
