# Generated by Django 4.2.7 on 2025-10-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0009_purchaseorder_admin_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='admin_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Administrative approval status for this purchase order', max_length=20, verbose_name='Admin Approval Status'),
        ),
    ]
