# Generated by Django 5.2.5 on 2025-10-23 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0010_alter_purchaseorder_admin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_person_name',
            field=models.CharField(blank=True, help_text='Primary contact person at supplier', max_length=100, verbose_name='Contact Person Name'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.CharField(blank=True, help_text='User who created this supplier', max_length=100, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department associated with this supplier', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='purchase_order.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='gst_number',
            field=models.CharField(blank=True, help_text='15-character GST Number', max_length=15, verbose_name='GST Number'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_by',
            field=models.CharField(blank=True, help_text='User who last updated this supplier', max_length=100, verbose_name='Last Updated By'),
        ),
    ]
