# Generated by Django 5.2.5 on 2025-10-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0011_supplier_contact_person_name_supplier_created_by_and_more'),
    ]

    operations = [
    ]
