# Generated by Django 5.2.5 on 2025-10-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0013_item_created_at_item_created_by_item_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_by',
            field=models.CharField(blank=True, help_text='User who last updated this supplier', max_length=100, verbose_name='Last Updated By'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_by',
            field=models.CharField(blank=True, help_text='User who created this supplier', max_length=100, verbose_name='Created By'),
        ),
    ]
