# Generated by Django 5.2.5 on 2025-10-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0014_purchaseorder_is_active_purchaseorder_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='calculation_method',
            field=models.CharField(choices=[('PLUS_TAX', 'Plus Tax (Add tax on base amount)'), ('REVERSE_TAX', 'Reverse Tax (Extract tax from total)')], default='PLUS_TAX', help_text='Plus Tax: Add tax to base price | Reverse Tax: Extract tax from inclusive price', max_length=20, verbose_name='Calculation Method'),
        ),
    ]
