# Generated by Django 5.2.5 on 2025-10-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0015_purchaseorder_calculation_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'verbose_name': 'Purchase Order Item', 'verbose_name_plural': 'Purchase Order Items'},
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='entry_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base price after tax extraction (for Reverse Tax method)', max_digits=12, verbose_name='Entry Rate'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Line Total'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tax Percentage'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Inclusive or exclusive price depending on calculation method', max_digits=12, verbose_name='Unit Price'),
        ),
    ]
