# Generated by Django 5.2.5 on 2025-10-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0016_alter_purchaseorderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sales price from Item Master MRP', max_digits=12, verbose_name='Sales Price (MRP)'),
        ),
    ]
