# Generated by Django 5.2.7 on 2025-12-04 10:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigning',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_unique_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('campaign_name', models.CharField(max_length=200)),
                ('software_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('number_of_days', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_reach', models.IntegerField(blank=True, default=0, null=True)),
                ('total_impression', models.IntegerField(blank=True, default=0, null=True)),
                ('total_leads', models.IntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-campaign_id'],
            },
        ),
    ]
