# Generated by Django 5.2.5 on 2025-11-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigning',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=200)),
                ('software_name', models.CharField(max_length=200)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('number_of_days', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_reach', models.IntegerField()),
                ('total_impression', models.IntegerField()),
                ('total_leads', models.IntegerField()),
            ],
        ),
    ]
