# Generated by Django 5.2.5 on 2025-11-28 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaigning',
            options={'ordering': ['-campaign_id']},
        ),
        migrations.AddField(
            model_name='campaigning',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='campaigning',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaigning',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
