# Generated by Django 5.2.5 on 2025-11-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaigning_options_campaigning_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigning',
            name='total_impression',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='campaigning',
            name='total_leads',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='campaigning',
            name='total_reach',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
