# Generated by Django 5.2.5 on 2025-11-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_alter_campaigning_total_impression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigning',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
