# Generated by Django 5.2.5 on 2025-11-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_campaigning_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigning',
            name='campaign_unique_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='campaigning',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
    ]
