# Generated by Django 5.2.7 on 2026-05-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Mobile / Tablet', 'Mobile / Tablet'), ('Monitor', 'Monitor'), ('Printer / Scanner', 'Printer / Scanner'), ('Networking Equipment', 'Networking Equipment'), ('Vehicle', 'Vehicle'), ('Furniture', 'Furniture'), ('Other', 'Other')], max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('spec_cpu', models.CharField(blank=True, max_length=100)),
                ('spec_ram', models.CharField(blank=True, max_length=100)),
                ('spec_storage', models.CharField(blank=True, max_length=100)),
                ('spec_display', models.CharField(blank=True, max_length=100)),
                ('spec_os', models.CharField(blank=True, max_length=100)),
                ('spec_color', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('returned', 'Returned')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
