# Generated by Django 5.2.7 on 2026-05-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0002_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/attachments/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='return_document',
            field=models.FileField(blank=True, null=True, upload_to='assignments/return_docs/'),
        ),
    ]
