# Generated by Django 5.2.7 on 2026-05-15 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0003_asset_image_assignment_attachment_and_more'),
        ('purchase_order', '0003_alter_item_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='purchase_order.department', verbose_name='Department'),
        ),
    ]
