# Generated by Django 5.2.7 on 2026-05-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0004_asset_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo of the asset (JPEG/PNG recommended).', null=True, upload_to='assets/images/'),
        ),
    ]
