# Generated by Django 5.2.7 on 2026-05-15 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0005_alter_asset_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentReturnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo taken at time of return (JPEG/PNG recommended).', upload_to='assignments/return_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_images', to='asset_management.assignment')),
            ],
            options={
                'verbose_name': 'Assignment Return Image',
                'verbose_name_plural': 'Assignment Return Images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
