# Generated by Django 5.2.7 on 2026-05-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0007_assignmentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='return_condition',
            field=models.TextField(blank=True),
        ),
    ]
