# Generated by Django 5.2.4 on 2025-10-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_capture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecapture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='captured_images/'),
        ),
        migrations.AddField(
            model_name='imagecapture',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imagecapture',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imagecapture',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
