# Generated by Django 5.2.4 on 2025-11-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_capture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecapture',
            name='link_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagecapture',
            name='link_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
