# Generated by Django 5.2.4 on 2025-10-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_capture', '0002_imagecapture_image_imagecapture_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagecapture',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='imagecapture',
            name='location_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='imagecapture',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='imagecapture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='captures/'),
        ),
    ]
