# Generated by Django 5.2.4 on 2025-10-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_capture', '0003_alter_imagecapture_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagecapture',
            options={},
        ),
        migrations.RemoveField(
            model_name='imagecapture',
            name='location_name',
        ),
        migrations.AlterField(
            model_name='imagecapture',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='imagecapture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='captured_images/'),
        ),
    ]
