# Generated by Django 5.2.6 on 2025-09-27 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_no', models.CharField(max_length=50, unique=True)),
                ('provider', models.CharField(max_length=100)),
                ('identify_person', models.CharField(blank=True, max_length=100, null=True)),
                ('incharge', models.CharField(blank=True, max_length=100, null=True)),
                ('last_recharge_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('validity', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SIMRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recharge_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recharged_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='sim_card.sim')),
            ],
            options={
                'ordering': ['-recharge_date'],
            },
        ),
    ]
