# Generated by Django 5.2.6 on 2025-09-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='validity',
        ),
        migrations.AddField(
            model_name='sim',
            name='validity_days',
            field=models.PositiveIntegerField(blank=True, help_text='Validity in number of days', null=True),
        ),
    ]
