# Generated by Django 5.2.6 on 2025-09-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_card', '0002_remove_sim_validity_sim_validity_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='validity_days',
        ),
        migrations.AddField(
            model_name='sim',
            name='validity_date',
            field=models.DateField(blank=True, help_text='Recharge valid until this date', null=True),
        ),
        migrations.AddField(
            model_name='simrecharge',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
