# Generated by Django 5.2.6 on 2025-10-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_card', '0003_remove_sim_validity_days_sim_validity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simrecharge',
            name='last_recharged_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
