# Generated by Django 5.2.6 on 2025-10-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim_card', '0004_simrecharge_last_recharged_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simrecharge',
            name='last_recharged_by',
        ),
    ]
