# Generated by Django 5.2.6 on 2025-10-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_card', '0005_remove_simrecharge_last_recharged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='validity_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='No. of days the recharge is valid', null=True),
        ),
        migrations.AddField(
            model_name='simrecharge',
            name='validity_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
