# Generated by Django 5.2.3 on 2025-10-31 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, choices=[('sales', 'Sales'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('it', 'IT'), ('admin', 'Administration'), ('other', 'Other')], max_length=50, null=True)),
                ('expense_type', models.CharField(choices=[('travel', 'Travel/Public Transport Expense'), ('food', 'Food/Meal Expense'), ('accommodation', 'Accommodation Expense'), ('fuel', 'Fuel/Parking and Toll Expense'), ('self', 'Self/Personal Expense')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='claimed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
