# Generated by Django 5.2.3 on 2025-10-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_name', models.CharField(max_length=200)),
                ('expense_type', models.CharField(choices=[('travel', 'Travel/Public Transport Expense'), ('food', 'Food/Meal Expense'), ('accommodation', 'Accommodation Expense'), ('fuel', 'Fuel Expense/Parking and Toll Expense')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('receipt', models.FileField(upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
