# Generated by Django 5.2.3 on 2025-10-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='claim_name',
        ),
    ]
