# Generated by Django 5.2.3 on 2025-10-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_remove_claim_claim_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='expense_type',
            field=models.CharField(choices=[('travel', 'Travel/Public Transport Expense'), ('food', 'Food/Meal Expense'), ('accommodation', 'Accommodation Expense'), ('fuel', 'Fuel/Parking and Toll Expense'), ('personal', 'Self/Personal Expense')], max_length=50),
        ),
    ]
