# Generated by Django 5.2.3 on 2025-11-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('claimed', 'Claimed'), ('Paid', 'Paid'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='claimed', max_length=20),
        ),
    ]
