# Generated by Django 5.2.3 on 2025-10-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_claim_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='client',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('claimed', 'Claimed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='claimed', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='expense_type',
            field=models.CharField(choices=[('travel', 'Travel/Public Transport Expense'), ('food', 'Food/Meal Expense'), ('accommodation', 'Accommodation Expense'), ('fuel', 'Fuel/Parking and Toll Expense'), ('self', 'Self/Personal Expense')], max_length=50),
        ),
    ]
