# Generated by Django 5.2.3 on 2025-11-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_alter_claim_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-created_at'], 'verbose_name': 'Claim', 'verbose_name_plural': 'Claims'},
        ),
        migrations.AlterField(
            model_name='claim',
            name='client',
            field=models.CharField(blank=True, help_text='Optional client code or identifier', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='client_name',
            field=models.CharField(blank=True, help_text='Optional client name (can be blank)', max_length=255, null=True),
        ),
    ]
