# Generated by Django 5.2.3 on 2025-12-17 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('multiple entry', 'Multiple Entry')], default='pending', help_text='Collection verification status', max_length=20)),
                ('collection_type', models.CharField(choices=[('cash', 'By Cash'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('neft payement', 'NEFT Payment')], default='cash', help_text='Payment mode used by the client', max_length=15)),
                ('client_name', models.CharField(help_text='Name of the client', max_length=255)),
                ('payment_method', models.CharField(default='cash', max_length=50)),
                ('branch', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount collected', max_digits=10)),
                ('paid_for', models.CharField(help_text='What the payment was for', max_length=255)),
                ('payment_screenshot', models.ImageField(help_text='Screenshot of the payment', upload_to='payment_screenshots/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_by', models.CharField(blank=True, help_text='User who created this collection', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=255)),
                ('requested_by', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('keyType', models.CharField(choices=[('Seat Upgradation Request', 'Seat Upgradation Request'), ('More Module Request', 'More Module Request'), ('Trade Name And Address Change Request', 'Trade Name And Address Change Request'), ('Key type Change Request', 'Key type Change Request'), ('Key Extension Request', 'Key Extension Request'), ('Hosted Key Request', 'Hosted Key Request'), ('Feeder Cancellation Request', 'Feeder Cancellation Request'), ('Demo Key Request', 'Demo Key Request'), ('Software Amount Change Request', 'Software Amount Change Request'), ('Maturity Upgradation Request', 'Maturity Upgradation Request'), ('Enterprises Key Request', 'Enterprises Key Request'), ('Image Request', 'Image Request')], max_length=255)),
                ('requestDate', models.DateField(blank=True, null=True)),
                ('gps_location', models.CharField(blank=True, max_length=100, null=True)),
                ('gps_address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('On Process', 'On Process'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('requested_status', models.CharField(choices=[('Requested', 'Requested'), ('Pending', 'Pending'), ('Delayed', 'Delayed'), ('Rejected', 'Rejected'), ('Working on it', 'Working on it'), ('Work completed/No payment', 'Work completed/No payment'), ('Work completed/Payment pending', 'Work completed/Payment pending'), ('Work done & Payment collected', 'Work done & Payment collected')], default='Requested', max_length=50)),
                ('requestImage', models.ImageField(blank=True, null=True, upload_to='key_request_images/')),
                ('branch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service_pack', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_system', models.CharField(blank=True, max_length=50, null=True)),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('license_key', models.TextField()),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.branch')),
            ],
        ),
    ]
