# Generated by Django 5.2.4 on 2025-08-07 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0189_lead_document'),
        ('app4', '0002_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.branch'),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
