# Generated by Django 5.0.2 on 2025-08-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
