# Generated by Django 5.2.3 on 2025-08-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0003_license_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=255)),
                ('request_title', models.CharField(max_length=255)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='key_requests/')),
                ('additional_requests', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
