# Generated by Django 5.0.2 on 2025-08-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0003_license_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='service_pack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
