# Generated by Django 5.0.2 on 2025-08-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0004_license_place_license_service_pack_license_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='number_of_system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
