# Generated by Django 5.2.3 on 2025-08-13 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0004_keyrequest'),
        ('app4', '0005_license_number_of_system'),
    ]

    operations = [
    ]
