# Generated by Django 5.2.3 on 2025-08-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0006_merge_0004_keyrequest_0005_license_number_of_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='module',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
