# Generated by Django 5.2.3 on 2025-08-27 12:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0189_lead_document'),
        ('app4', '0007_license_module_license_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyrequest',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='keyrequest',
            old_name='client_name',
            new_name='clientName',
        ),
        migrations.RenameField(
            model_name='keyrequest',
            old_name='request_title',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='additional_requests',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='image_file',
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.branch'),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='keyType',
            field=models.CharField(choices=[('Seat Upgradation Request', 'Seat Upgradation Request'), ('More Module Request', 'More Module Request'), ('Trade Name And Address Change Request', 'Trade Name And Address Change Request'), ('Key type Change Request', 'Key type Change Request'), ('Key Extension Request', 'Key Extension Request'), ('Hosted Key Request', 'Hosted Key Request'), ('Feeder Cancellation Request', 'Feeder Cancellation Request'), ('Demo Key Request', 'Demo Key Request'), ('Software Amount Change Request', 'Software Amount Change Request'), ('Maturity Upgradation Request', 'Maturity Upgradation Request'), ('Enterprises Key Request', 'Enterprises Key Request'), ('Image Request', 'Image Request')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='requestDate',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='requestImage',
            field=models.ImageField(blank=True, null=True, upload_to='key_request_images/'),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On Process', 'On Process'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
