# Generated by Django 5.2.3 on 2025-08-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0008_alter_keyrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyrequest',
            name='requestedStatus',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Working on it', 'Working on it'), ('Work Completed & Payment Pending', 'Work Completed & Payment Pending'), ('Payment Collected & Done', 'Payment Collected & Done')], default='Requested', max_length=50),
        ),
    ]
