# Generated by Django 5.2.3 on 2025-08-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0008_alter_keyrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyrequest',
            name='bcare',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='cancelReason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='currentAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='currentKeyType',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='currentMaturity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='enterpriseDetails',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='extensionPeriod',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='icare',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='module',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='newAddress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='newFirmName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='requiredAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='requiredKeyType',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='requiredMaturity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='requiredSeats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='serverDetails',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='task',
            field=models.TextField(blank=True),
        ),
    ]
