# Generated by Django 5.2.3 on 2025-08-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0009_keyrequest_bcare_keyrequest_cancelreason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyrequest',
            name='bcare',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='cancelReason',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='currentAmount',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='currentKeyType',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='currentMaturity',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='enterpriseDetails',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='extensionPeriod',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='icare',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='module',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='newAddress',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='newFirmName',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='requiredAmount',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='requiredKeyType',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='requiredMaturity',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='requiredSeats',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='serverDetails',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='task',
        ),
    ]
