# Generated by Django 5.2.3 on 2025-08-30 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0009_keyrequest_requestedstatus'),
        ('app4', '0010_remove_keyrequest_bcare_and_more'),
    ]

    operations = [
    ]
