# Generated by Django 5.2.3 on 2025-08-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0011_merge_20250830_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyrequest',
            name='requestedStatus',
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='requested_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Working on it', 'Working on it'), ('Work completed/Payment pending', 'Work completed/Payment pending'), ('Work done & Payment collected', 'Work done & Payment collected')], default='Requested', max_length=50),
        ),
        migrations.AlterField(
            model_name='keyrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On Process', 'On Process'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
