# Generated by Django 5.2.3 on 2025-09-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0012_remove_keyrequest_requestedstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyrequest',
            name='gps_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
