# Generated by Django 5.2.3 on 2025-09-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0013_keyrequest_gps_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyrequest',
            name='gps_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
