# Generated by Django 5.2.3 on 2025-09-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0014_keyrequest_gps_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyrequest',
            name='branch',
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
