# Generated by Django 5.0.2 on 2025-09-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0015_remove_keyrequest_branch_keyrequest_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyrequest',
            name='requested_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Working on it', 'Working on it'), ('Work completed/Payment pending', 'Work completed/Payment pending'), ('Work done & Payment collected', 'Work done & Payment collected')], default='Requested', max_length=50),
        ),
    ]
