# Generated by Django 5.2.3 on 2025-09-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0016_alter_keyrequest_requested_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Name of the client', max_length=255)),
                ('branch', models.CharField(help_text='Branch name', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount collected', max_digits=10)),
                ('paid_for', models.CharField(help_text='What the payment was for', max_length=255)),
                ('payment_screenshot', models.ImageField(help_text='Screenshot of the payment', upload_to='payment_screenshots/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['-created_at'],
            },
        ),
    ]
