# Generated by Django 5.2.3 on 2025-09-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0017_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyrequest',
            name='requested_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
