# Generated by Django 5.2.3 on 2025-09-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0019_alter_keyrequest_requested_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyrequest',
            name='requested_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Pending', 'Pending'), ('Delayed', 'Delayed'), ('Rejected', 'Rejected'), ('Working on it', 'Working on it'), ('Work completed/No payment', 'Work completed/No payment'), ('Work completed/Payment pending', 'Work completed/Payment pending'), ('Work done & Payment collected', 'Work done & Payment collected')], default='Requested', max_length=50),
        ),
    ]
