# Generated by Django 5.2.3 on 2025-09-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0020_alter_keyrequest_requested_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='created_by',
            field=models.CharField(blank=True, help_text='User who created this collection', max_length=255, null=True),
        ),
    ]
