# Generated by Django 5.2.3 on 2025-09-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0021_collection_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', help_text='Collection verification status', max_length=20),
        ),
    ]
