# Generated by Django 5.2.3 on 2025-09-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0022_collection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_type',
            field=models.CharField(choices=[('cash', 'By Cash'), ('online', 'Online Payment'), ('cheque', 'Cheque')], default='cash', help_text='Payment mode used by the client', max_length=10),
        ),
    ]
