# Generated by Django 5.2.3 on 2025-10-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0023_collection_collection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_type',
            field=models.CharField(choices=[('cash', 'By Cash'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('neft payement', 'NEFT Payment')], default='cash', help_text='Payment mode used by the client', max_length=15),
        ),
    ]
