# Generated by Django 5.2.3 on 2025-10-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0024_alter_collection_collection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('multiple entry', 'Multiple Entry')], default='pending', help_text='Collection verification status', max_length=20),
        ),
    ]
