# Generated by Django 5.2.3 on 2025-10-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0025_alter_collection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='payment_method',
            field=models.CharField(default='cash', max_length=50),
        ),
    ]
