# Generated by Django 5.2.3 on 2025-11-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='wallet_pdfs/'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='pdf_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='upload_type',
            field=models.CharField(choices=[('bank', 'Bank/Details'), ('qr', 'QR Code'), ('document', 'Documentation Image'), ('pdf', 'PDF Document'), ('other', 'Other Wallet')], max_length=20),
        ),
    ]
