# Generated by Django 5.2.3 on 2025-11-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bank_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='other_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wallet',
            name='qr_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wallet_images/'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='upload_type',
            field=models.CharField(choices=[('bank', 'Bank/Details'), ('qr', 'QR Code'), ('document', 'Documentation Image'), ('other', 'Other Wallet')], max_length=20),
        ),
    ]
