# Generated by Django 5.2.3 on 2025-11-19 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuel_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_number', models.CharField(max_length=100, unique=True)),
                ('challan_date', models.DateField()),
                ('offense_type', models.CharField(max_length=200)),
                ('offense_location', models.CharField(blank=True, max_length=300, null=True)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel_entry', models.ForeignKey(blank=True, help_text='Related fuel entry that this challan is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challans', to='fuel_management.fuelentry')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challans', to='fuel_management.vehicle')),
            ],
            options={
                'ordering': ['-challan_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_date', models.DateField()),
                ('description', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details', to='fuel_management.vehicle')),
            ],
            options={
                'db_table': 'vehicle_challan_vehicledetail',
                'ordering': ['-detail_date'],
            },
        ),
    ]
