# Generated by Django 5.0.2 on 2025-10-13 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0191_leaverequest_note'),
        ('app2', '0056_standbyreturn_standbyimage_standby_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('logged', 'Logged'), ('sent_technician', 'Sent To Technician'), ('accepted', 'In Technician Hand'), ('pending', 'Pending'), ('completed', 'Completed'), ('returned', 'Returned'), ('rejected', 'Rejected')], default='logged', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('technician', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('self_assigned', models.BooleanField(default=False, help_text='True if the job was self-assigned by the creator')),
                ('standby_issued', models.BooleanField(default=False, help_text='Whether standby equipment was issued')),
                ('items_data', models.JSONField(blank=True, default=list, help_text='Stores array of items with their complaints')),
                ('completion_details', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcards', to='app1.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='jobcard_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item_index', models.IntegerField(default=0, help_text='Index of item in items_data array')),
                ('complaint_index', models.IntegerField(default=0, help_text='Index of complaint within item')),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app5.jobcard')),
            ],
            options={
                'ordering': ['item_index', 'complaint_index', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StandbyIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_to', models.CharField(max_length=200)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return_date', models.DateTimeField()),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='issued', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('condition_on_issue', models.TextField(blank=True, help_text='Condition notes when issued')),
                ('condition_on_return', models.TextField(blank=True, help_text='Condition notes when returned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_standby_items', to='app1.user')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standby_issuances', to='app5.jobcard')),
                ('standby_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuances', to='app2.standbyitem')),
            ],
            options={
                'verbose_name': 'Standby Issuance',
                'verbose_name_plural': 'Standby Issuances',
                'ordering': ['-issued_date'],
            },
        ),
    ]
