# Generated by Django 5.0.2 on 2025-08-22 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('items_data', models.JSONField(default=list, help_text='Stores array of items with their complaints')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='jobcard_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item_index', models.IntegerField(default=0, help_text='Index of item in items_data array')),
                ('complaint_index', models.IntegerField(default=0, help_text='Index of complaint within item')),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app5.jobcard')),
            ],
            options={
                'ordering': ['item_index', 'complaint_index', 'uploaded_at'],
            },
        ),
    ]
