# Generated by Django 5.2.7 on 2025-11-26 08:58

import app5.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0001_initial'),
        ('app2', '0001_initial'),
        ('purchase_order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('self_assigned', 'Self Assigned'), ('unassigned', 'Unassigned')], default='unassigned', max_length=20)),
                ('ticket_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('ownerName', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customerType', models.CharField(default='Business', max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('District', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('pinCode', models.CharField(blank=True, max_length=10, null=True)),
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('individualAddress', models.TextField(blank=True, null=True)),
                ('individualPlace', models.CharField(blank=True, max_length=100, null=True)),
                ('individualDistrict', models.CharField(blank=True, max_length=100, null=True)),
                ('individualState', models.CharField(blank=True, max_length=100, null=True)),
                ('individualPinCode', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('refFrom', models.CharField(blank=True, max_length=100, null=True)),
                ('business', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('marketedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('Consultant', models.CharField(blank=True, max_length=100, null=True)),
                ('requirement', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('assigned_to_name', models.CharField(blank=True, max_length=150, null=True)),
                ('assigned_by_name', models.CharField(blank=True, max_length=150, null=True)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('assigned_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_name', models.CharField(max_length=255, verbose_name='Reference Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
                'db_table': 'reference_master',
            },
        ),
        migrations.CreateModel(
            name='RequirementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='Item Name')),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Owner Name')),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Requirement Item',
                'verbose_name_plural': 'Requirement Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(max_length=25)),
                ('customer_address', models.TextField()),
                ('technician', models.CharField(max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial Payment')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Billing',
                'verbose_name_plural': 'Service Billings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='State Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'State Master',
                'verbose_name_plural': 'State Masters',
                'db_table': 'state_master',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this supplier is currently active', verbose_name='Active Status')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('logged', 'Logged'), ('sent_technician', 'Sent To Technician'), ('accepted', 'In Technician Hand'), ('pending', 'Pending'), ('completed', 'Completed'), ('returned', 'Returned'), ('rejected', 'Rejected')], default='logged', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('technician', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('self_assigned', models.BooleanField(default=False, help_text='True if the job was self-assigned by the creator')),
                ('standby_issued', models.BooleanField(default=False, help_text='Whether standby equipment was issued')),
                ('items_data', models.JSONField(blank=True, default=list, help_text='Stores array of items with their complaints')),
                ('completion_details', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcards', to='app1.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='jobcard_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item_index', models.IntegerField(default=0, help_text='Index of item in items_data array')),
                ('complaint_index', models.IntegerField(default=0, help_text='Index of complaint within item')),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app5.jobcard')),
            ],
            options={
                'ordering': ['item_index', 'complaint_index', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
                'ordering': ['-return_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app5.models.return_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('return_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app5.returnitem')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('serial_no', models.CharField(blank=True, max_length=50, null=True)),
                ('service_description', models.TextField()),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_status', models.CharField(choices=[('Payment', 'Payment'), ('Free', 'Free')], default='Payment', help_text='Whether this service is paid or free', max_length=20)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='app5.servicebilling')),
            ],
        ),
        migrations.CreateModel(
            name='StandbyIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_to', models.CharField(max_length=200)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return_date', models.DateTimeField()),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='issued', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('condition_on_issue', models.TextField(blank=True, help_text='Condition notes when issued')),
                ('condition_on_return', models.TextField(blank=True, help_text='Condition notes when returned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_standby_items', to='app1.user')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standby_issuances', to='app5.jobcard')),
                ('standby_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuances', to='app2.standbyitem')),
            ],
            options={
                'verbose_name': 'Standby Issuance',
                'verbose_name_plural': 'Standby Issuances',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(max_length=50, unique=True)),
                ('selected_item', models.CharField(max_length=200)),
                ('item_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Sent to Supplier'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('supplier_response', models.TextField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_tickets', to='app5.jobcard')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranty_tickets', to='purchase_order.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('performed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('warranty_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app5.warrantyticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='returnitem',
            name='warranty_ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_item', to='app5.warrantyticket'),
        ),
        migrations.AddConstraint(
            model_name='warrantyticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'submitted', 'approved'])), fields=('selected_item', 'item_serial', 'status'), name='unique_active_warranty_per_item'),
        ),
    ]
