# Generated by Django 5.2.7 on 2025-11-05 06:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
        ('purchase_order', '0002_purchaseorderitem_sales_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('ownerName', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customerType', models.CharField(default='Business', max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('District', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('pinCode', models.CharField(blank=True, max_length=10, null=True)),
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('individualAddress', models.TextField(blank=True, null=True)),
                ('individualPlace', models.CharField(blank=True, max_length=100, null=True)),
                ('individualDistrict', models.CharField(blank=True, max_length=100, null=True)),
                ('individualState', models.CharField(blank=True, max_length=100, null=True)),
                ('individualPinCode', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('refFrom', models.CharField(blank=True, max_length=100, null=True)),
                ('business', models.CharField(blank=True, max_length=100, null=True)),
                ('marketedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('Consultant', models.CharField(blank=True, max_length=100, null=True)),
                ('requirement', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='service_status',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Free', 'Free')], default='Payment', help_text='Whether this service is paid or free', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this supplier is currently active', verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='servicebilling',
            name='customer_contact',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='warrantyticket',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranty_tickets', to='purchase_order.supplier'),
        ),
    ]
