# Generated by Django 4.2.7 on 2025-11-20 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
    ]
