# Generated by Django 5.2.7 on 2026-04-29 09:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_initial'),
        ('app5', '0001_initial'),
        ('purchase_order', '0003_alter_item_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Master',
                'verbose_name_plural': 'Tax Masters',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='app1.user'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='proposal_attachment',
            field=models.FileField(blank=True, help_text='Optional proposal document (PDF, Word, etc.) attached to this quotation', null=True, upload_to='quotation_proposals/'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phoneNo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField()),
                ('contact_method', models.CharField(choices=[('Phone Call', 'Phone Call'), ('WhatsApp', 'WhatsApp'), ('Email', 'Email'), ('SMS', 'SMS'), ('In-Person Meeting', 'In-Person Meeting'), ('Other', 'Other')], max_length=50)),
                ('reply', models.TextField(help_text='Remarks or notes from the conversation')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Follow-up Required', 'Follow-up Required'), ('Not Attanted', 'Not Attanted'), ('Proposal Sent', 'Proposal Sent'), ('On Hold', 'On Hold'), ('Rejected', 'Rejected')], max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('selected_requirement_items', models.TextField(blank=True, help_text='Comma-separated list of requirement items that need follow-up', null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_followups', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='app5.lead')),
            ],
            options={
                'verbose_name': 'Follow Up',
                'verbose_name_plural': 'Follow Ups',
                'ordering': ['-follow_up_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(max_length=50, unique=True)),
                ('so_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('payment_terms', models.CharField(blank=True, choices=[('DUE_ON_RECEIPT', 'Due on Receipt'), ('NET_15', 'Net 15 Days'), ('NET_30', 'Net 30 Days'), ('NET_45', 'Net 45 Days'), ('NET_60', 'Net 60 Days')], default='NET_30', max_length=20, null=True)),
                ('calculation_method', models.CharField(blank=True, choices=[('STANDARD', 'Standard Calculation'), ('TAX_INCLUSIVE', 'Tax Inclusive'), ('TAX_EXCLUSIVE', 'Tax Exclusive'), ('DISCOUNT_FIRST', 'Discount First'), ('DISCOUNT_LAST', 'Discount Last'), ('CUSTOM', 'Custom Calculation')], default='STANDARD', max_length=20, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='app5.customer')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_from', to='purchase_order.department')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_to', to='purchase_order.department')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sales_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-so_date', '-so_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=15)),
                ('entry_rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('item_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='purchase_order.item')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app5.salesorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['so_number'], name='app5_saleso_so_numb_868774_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status'], name='app5_saleso_status_5c7c44_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['so_date'], name='app5_saleso_so_date_bb295a_idx'),
        ),
    ]
