# Generated by Django 6.0.2 on 2026-02-23 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_initial'),
        ('app5', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='app1.user'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phoneNo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField()),
                ('contact_method', models.CharField(choices=[('Phone Call', 'Phone Call'), ('WhatsApp', 'WhatsApp'), ('Email', 'Email'), ('SMS', 'SMS'), ('In-Person Meeting', 'In-Person Meeting'), ('Other', 'Other')], max_length=50)),
                ('reply', models.TextField(help_text='Remarks or notes from the conversation')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Follow-up Required', 'Follow-up Required'), ('Not Attanted', 'Not Attanted'), ('Proposal Sent', 'Proposal Sent'), ('On Hold', 'On Hold'), ('Rejected', 'Rejected')], max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('selected_requirement_items', models.TextField(blank=True, help_text='Comma-separated list of requirement items that need follow-up', null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_followups', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='app5.lead')),
            ],
            options={
                'verbose_name': 'Follow Up',
                'verbose_name_plural': 'Follow Ups',
                'ordering': ['-follow_up_date', '-created_at'],
            },
        ),
    ]
