# Generated by Django 5.2.7 on 2026-01-12 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
        ('purchase_order', '0003_alter_item_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_order.item', verbose_name='Item'),
        ),
    ]
