# Generated by Django 5.2.5 on 2025-11-06 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
        ('purchase_order', '0002_department_logo_purchaseorderitem_sales_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='service_status',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Free', 'Free')], default='Payment', help_text='Whether this service is paid or free', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this supplier is currently active', verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='servicebilling',
            name='customer_contact',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='warrantyticket',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranty_tickets', to='purchase_order.supplier'),
        ),
    ]
