# Generated by Django 5.2.7 on 2025-12-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0002_quotation_quotationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='customerType',
            field=models.CharField(default='Business', help_text='Determines which input group to show', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=20),
        ),
    ]
