# Generated by Django 5.2.5 on 2025-10-18 06:02

import app5.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0002_warrantyticket_warrantyitemlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Sent to Supplier'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warranty_ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_item', to='app5.warrantyticket')),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
                'ordering': ['-return_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app5.models.return_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('return_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app5.returnitem')),
            ],
        ),
    ]
