# Generated by Django 5.2.7 on 2025-11-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0002_lead_requirementitem_serviceitem_service_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
