# Generated by Django 5.2.7 on 2026-01-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0002_requirementitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementitem',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='app5.lead'),
        ),
    ]
