# Generated by Django 5.2.7 on 2025-12-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0003_alter_lead_customertype_alter_lead_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementitem',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ticket Number'),
        ),
    ]
