# Generated by Django 5.2.7 on 2026-06-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0003_lead_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='department',
        ),
    ]
