# Generated by Django 5.2.5 on 2025-10-23 04:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0003_alter_warrantyticket_status_returnitem_returnimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(max_length=15)),
                ('customer_address', models.TextField()),
                ('technician', models.CharField(max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial Payment')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Billing',
                'verbose_name_plural': 'Service Billings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('serial_no', models.CharField(blank=True, max_length=50, null=True)),
                ('service_description', models.TextField()),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='app5.servicebilling')),
            ],
        ),
    ]
