# Generated by Django 5.2.7 on 2025-11-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0003_businessnature'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='State Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'State Master',
                'verbose_name_plural': 'State Masters',
                'db_table': 'state_master',
                'ordering': ['name'],
            },
        ),
    ]
