# Generated by Django 5.2.7 on 2026-01-29 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_initial'),
        ('app5', '0003_alter_requirementitem_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to='app1.user'),
        ),
    ]
