# Generated by Django 5.2.7 on 2025-10-28 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0004_servicebilling_serviceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyticket',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranty_tickets', to='app5.supplier'),
        ),
    ]
