# Generated by Django 5.2.7 on 2025-12-18 09:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0004_requirementitem_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementitem',
            name='lead',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='app5.lead'),
            preserve_default=False,
        ),
    ]
