# Generated by Django 5.2.7 on 2025-11-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0004_statemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assignment_type',
            field=models.CharField(choices=[('self_assigned', 'Self Assigned'), ('unassigned', 'Unassigned')], default='unassigned', max_length=20),
        ),
    ]
