# Generated by Django 5.2.5 on 2025-08-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0004_alter_jobcardimage_options_remove_jobcard_items_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcardimage',
            options={'ordering': ['item_index', 'complaint_index', 'uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='complaint_description',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='complaint_notes',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='config',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='item',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='status',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='items_data',
            field=models.JSONField(default=list, help_text='Stores array of items with their complaints'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobcardimage',
            name='complaint_index',
            field=models.IntegerField(default=0, help_text='Index of complaint within item'),
        ),
        migrations.AddField(
            model_name='jobcardimage',
            name='item_index',
            field=models.IntegerField(default=0, help_text='Index of item in items_data array'),
        ),
    ]
