# Generated by Django 5.2.7 on 2025-11-07 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_initial'),
        ('app5', '0005_lead_assignment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_leads', to='app1.user'),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='app1.user'),
        ),
    ]
