# Generated by Django 5.2.5 on 2025-08-25 06:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0005_alter_jobcardimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcardimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='items_data',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='jobcardimage',
            name='complaint_index',
        ),
        migrations.RemoveField(
            model_name='jobcardimage',
            name='item_index',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='complaint_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='complaint_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='config',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='item',
            field=models.CharField(choices=[('Mouse', 'Mouse'), ('Keyboard', 'Keyboard'), ('CPU', 'CPU'), ('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Printer', 'Printer'), ('Monitor', 'Monitor'), ('Other', 'Other')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcard',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('logged', 'Logged'), ('sent_technician', 'Sent To Technician'), ('pending', 'Pending'), ('completed', 'Completed'), ('returned', 'Returned'), ('rejected', 'Rejected')], default='logged', max_length=20),
        ),
    ]
