# Generated by Django 5.2.7 on 2025-10-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0005_alter_warrantyticket_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this supplier is currently active', verbose_name='Active Status'),
        ),
    ]
