# Generated by Django 5.2.7 on 2025-10-29 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0006_supplier_is_active'),
        ('purchase_order', '0016_alter_purchaseorderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyticket',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranty_tickets', to='purchase_order.supplier'),
        ),
    ]
