# Generated by Django 5.2.7 on 2025-11-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0006_lead_assigned_by_lead_assigned_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
