# Generated by Django 5.2.7 on 2025-10-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0007_alter_warrantyticket_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('payment', 'Payment')], default='payment', max_length=10),
        ),
    ]
