# Generated by Django 5.2.7 on 2025-11-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0007_remove_lead_assigned_by_remove_lead_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirementitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Requirement Item', 'verbose_name_plural': 'Requirement Items'},
        ),
        migrations.AddField(
            model_name='requirementitem',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='requirementitem',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Owner Name'),
        ),
        migrations.AddField(
            model_name='requirementitem',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='requirementitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='requirementitem',
            name='item_name',
            field=models.CharField(max_length=200, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='requirementitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='requirementitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='requirementitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit'),
        ),
    ]
