# Generated by Django 5.2.7 on 2026-02-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0007_customer_quotation_proposal_attachment_salesorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='proposal_attachment',
            field=models.FileField(blank=True, help_text='Optional proposal document (PDF, Word, etc.) attached to this quotation', null=True, upload_to='quotation_proposals/'),
        ),
    ]
