# Generated by Django 5.2.7 on 2025-10-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0008_serviceitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='status',
        ),
        migrations.AlterField(
            model_name='servicebilling',
            name='customer_contact',
            field=models.CharField(max_length=25),
        ),
    ]
