# Generated by Django 5.2.7 on 2026-02-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0008_alter_quotation_proposal_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Master',
                'verbose_name_plural': 'Tax Masters',
                'ordering': ['name'],
            },
        ),
    ]
