# Generated by Django 5.2.7 on 2025-10-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0009_remove_serviceitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='service_status',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Free', 'Free')], default='Payment', help_text='Whether this service is paid or free', max_length=20),
        ),
    ]
