# Generated by Django 5.2.7 on 2026-02-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0009_taxmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
