# Generated by Django 5.2.5 on 2025-08-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0009_alter_jobcardimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('logged', 'Logged'), ('sent_technician', 'Sent To Technician'), ('pending', 'Pending'), ('completed', 'Completed'), ('returned', 'Returned'), ('rejected', 'Rejected')], default='logged', max_length=20),
        ),
    ]
