# Generated by Django 5.2.7 on 2026-03-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0010_salesorder_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
    ]
