# Generated by Django 5.2.5 on 2025-08-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0012_alter_item_options_item_created_at_item_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
    ]
