# Generated by Django 5.2.5 on 2025-08-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0013_remove_item_created_at_remove_item_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AddField(
            model_name='jobcard',
            name='technician',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
