# Generated by Django 5.2.5 on 2025-09-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0014_alter_item_options_jobcard_technician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
