# Generated by Django 5.2.5 on 2025-09-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0015_alter_jobcard_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
