# Generated by Django 5.2.5 on 2025-09-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0016_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='sl_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
