# Generated by Django 5.2.5 on 2025-09-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0017_supplier_sl_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='sl_no',
        ),
    ]
