# Generated by Django 5.2.5 on 2025-09-11 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0018_remove_supplier_sl_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='serial_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
