# Generated by Django 5.2.5 on 2025-09-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0019_supplier_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='completion_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
