# Generated by Django 5.2.5 on 2025-09-19 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0189_lead_document'),
        ('app5', '0020_jobcard_completion_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='address',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='completion_details',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='technician',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='complaints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcards', to='app1.user'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='customer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='ticket_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
