# Generated by Django 5.2.5 on 2025-09-19 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0021_remove_jobcard_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='complaints',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='created_by',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcard',
            name='completion_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcard',
            name='technician',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='customer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
