# Generated by Django 5.2.5 on 2025-09-19 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0189_lead_document'),
        ('app5', '0024_remove_jobcard_creator_jobcard_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='created_by',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcards', to='app1.user'),
        ),
    ]
