# Generated by Django 5.2.5 on 2025-09-19 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0025_remove_jobcard_created_by_jobcard_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='creator',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcards', to=settings.AUTH_USER_MODEL),
        ),
    ]
