# Generated by Django 5.2.5 on 2025-09-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0027_alter_jobcard_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='created_by',
        ),
    ]
