# Generated by Django 5.2.5 on 2025-09-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0029_jobcard_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='created_by',
            field=models.CharField(blank=True, help_text='Name/username of the person who created this job card', max_length=100, null=True),
        ),
    ]
