# Generated by Django 5.2.5 on 2025-09-19 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0189_lead_document'),
        ('app5', '0030_alter_jobcard_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcards', to='app1.user'),
        ),
    ]
