# Generated by Django 4.2.7 on 2025-11-12 04:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('late', 'Late'), ('early', 'Early'), ('leave', 'Leave'), ('wfh', 'Work From Home')], max_length=20)),
                ('request_id', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employee')),
            ],
        ),
    ]
