# Generated by Django 5.2.7 on 2025-11-26 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cancel_Requestes', '0001_initial'),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employee'),
        ),
    ]
