# Generated by Django 5.2.3 on 2025-12-08 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_details', models.TextField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('is_approved', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_experience_certificates', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_experience_certificates', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experience_certificate', to='app1.employee')),
            ],
            options={
                'verbose_name': 'Experience Certificate',
                'verbose_name_plural': 'Experience Certificates',
                'db_table': 'experience_certificates',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('cv_attachment', models.FileField(blank=True, null=True, upload_to='cv_attachments/')),
                ('place', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('education', models.CharField(max_length=255)),
                ('experience', models.TextField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cv_source', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notice_period', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_generated', models.BooleanField(default=False)),
                ('generated_date', models.DateTimeField(blank=True, null=True)),
                ('candidate_status', models.CharField(blank=True, choices=[('willing', 'Willing'), ('not_willing', 'Not Willing')], default=None, max_length=15, null=True)),
                ('status_remarks', models.TextField(blank=True, null=True)),
                ('status_updated_date', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_offer_letters', to=settings.AUTH_USER_MODEL)),
                ('interview', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter', to='app3.interview')),
                ('status_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updated_offer_letters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.IntegerField(blank=True, default=0, null=True)),
                ('knowledge', models.IntegerField(blank=True, default=0, null=True)),
                ('confidence', models.IntegerField(blank=True, default=0, null=True)),
                ('attitude', models.IntegerField(blank=True, default=0, null=True)),
                ('communication', models.IntegerField(blank=True, default=0, null=True)),
                ('languages', models.CharField(blank=True, default='', max_length=255)),
                ('expected_salary', models.CharField(blank=True, default='', max_length=50)),
                ('experience', models.TextField(blank=True, default='')),
                ('remark', models.TextField(blank=True, default='')),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='voice_notes/')),
                ('status', models.CharField(choices=[('selected', 'Selected'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.interview')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_certificates', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_certificates', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employee')),
            ],
        ),
    ]
