# Generated by Django 5.2.1 on 2025-06-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarycertificate',
            old_name='salary_amount',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='salarycertificate',
            name='created_at',
        ),
    ]
