# Generated by Django 5.2.1 on 2025-06-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_rename_salary_amount_salarycertificate_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycertificate',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salarycertificate',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarycertificate',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
