# Generated by Django 5.2.2 on 2025-06-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_salarycertificate_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycertificate',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
