# Generated by Django 5.2.2 on 2025-06-09 09:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0174_delete_employeesalary'),
        ('app3', '0004_salarycertificate_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycertificate',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_certificates', to='app1.user'),
        ),
        migrations.AddField(
            model_name='salarycertificate',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarycertificate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_certificates', to='app1.user'),
        ),
    ]
