# Generated by Django 5.2.2 on 2025-06-09 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0174_delete_employeesalary'),
        ('app3', '0006_alter_salarycertificate_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarycertificate',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_certificates', to='app1.user'),
        ),
        migrations.AlterField(
            model_name='salarycertificate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_certificates', to='app1.user'),
        ),
    ]
