# Generated by Django 5.2.2 on 2025-06-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0009_salarycertificate_added_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarycertificate',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='salarycertificate',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='salarycertificate',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='salarycertificate',
            name='approved_on',
        ),
    ]
