# Generated by Django 5.2.2 on 2025-06-09 12:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0010_remove_salarycertificate_added_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycertificate',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarycertificate',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarycertificate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarycertificate',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
