# Generated by Django 5.2.3 on 2025-06-12 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0012_interview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.IntegerField()),
                ('knowledge', models.IntegerField()),
                ('confidence', models.IntegerField()),
                ('attitude', models.IntegerField()),
                ('communication', models.IntegerField()),
                ('languages', models.CharField(max_length=255)),
                ('expected_salary', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('remark', models.TextField()),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.interview')),
            ],
        ),
    ]
