# Generated by Django 5.2.3 on 2025-06-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0013_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='voice_notes/'),
        ),
    ]
