# Generated by Django 5.2.3 on 2025-06-17 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0014_rating_voice_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notice_period', models.IntegerField()),
                ('interview', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app3.interview')),
            ],
        ),
    ]
