# Generated by Django 5.2.3 on 2025-06-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0015_offerletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerletter',
            name='interview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter', to='app3.interview'),
        ),
    ]
