# Generated by Django 5.2.3 on 2025-06-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0016_alter_offerletter_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
    ]
