# Generated by Django 5.2.3 on 2025-06-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0017_offerletter_is_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='status',
            field=models.CharField(choices=[('selected', 'Selected'), ('rejected', 'Rejected')], default='selected', max_length=10),
        ),
    ]
