# Generated by Django 5.2.3 on 2025-06-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0018_rating_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
    ]
