# Generated by Django 5.2.3 on 2025-06-20 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0019_offerletter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerletter',
            name='status',
        ),
    ]
