# Generated by Django 5.2.3 on 2025-06-20 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0020_remove_offerletter_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_offer_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='generated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
