# Generated by Django 5.2.3 on 2025-06-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0021_offerletter_generated_by_offerletter_generated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='appearance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='attitude',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='communication',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='confidence',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='expected_salary',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='knowledge',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='languages',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rating',
            name='remark',
            field=models.TextField(blank=True, default=''),
        ),
    ]
