# Generated by Django 5.2.3 on 2025-06-20 07:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0022_alter_rating_appearance_alter_rating_attitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerletter',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
