# Generated by Django 5.2.3 on 2025-06-21 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0023_offerletter_end_time_offerletter_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='candidate_status',
            field=models.CharField(blank=True, choices=[('willing', 'Willing'), ('not_willing', 'Not Willing')], default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='status_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updated_offer_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='status_updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
