# Generated by Django 5.2.3 on 2025-06-27 05:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0179_servicelog_place'),
        ('app3', '0025_alter_rating_status_experiencecertificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperienceCertificate',
            new_name='ExperienceCertificateDetails',
        ),
    ]
