# Generated by Django 5.2.3 on 2025-06-27 05:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0179_servicelog_place'),
        ('app3', '0026_rename_experiencecertificate_experiencecertificatedetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperienceCertificateDetails',
            new_name='ExperienceCertificate',
        ),
    ]
