# Generated by Django 5.2.3 on 2025-06-27 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0027_rename_experiencecertificatedetails_experiencecertificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencecertificate',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='experiencecertificate',
            name='experience_details',
        ),
        migrations.AddField(
            model_name='experiencecertificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='experiencecertificate',
            name='experience_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencecertificate',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_certificates_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experiencecertificate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_certificates_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
