# Generated by Django 5.2.3 on 2025-06-27 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0028_remove_experiencecertificate_certificate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencecertificate',
            old_name='certificate_file',
            new_name='certificate',
        ),
        migrations.RenameField(
            model_name='experiencecertificate',
            old_name='experience_note',
            new_name='experience_details',
        ),
        migrations.AlterField(
            model_name='experiencecertificate',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_experience_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experiencecertificate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_experience_certificates', to=settings.AUTH_USER_MODEL),
        ),
    ]
