# Generated by Django 5.2.3 on 2025-06-27 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0179_servicelog_place'),
        ('app3', '0029_rename_certificate_file_experiencecertificate_certificate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencecertificate',
            options={'verbose_name': 'Experience Certificate', 'verbose_name_plural': 'Experience Certificates'},
        ),
        migrations.RemoveField(
            model_name='experiencecertificate',
            name='address',
        ),
        migrations.RemoveField(
            model_name='experiencecertificate',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='experiencecertificate',
            name='joining_date',
        ),
        migrations.AlterField(
            model_name='experiencecertificate',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experience_certificate', to='app1.employee'),
        ),
        migrations.AlterModelTable(
            name='experiencecertificate',
            table='experience_certificates',
        ),
    ]
