# Generated by Django 5.2.3 on 2025-06-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0030_alter_experiencecertificate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencecertificate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiencecertificate',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
