# Generated by Django 5.2.3 on 2025-06-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0032_alter_experiencecertificate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencecertificate',
            options={'verbose_name': 'Experience Certificate', 'verbose_name_plural': 'Experience Certificates'},
        ),
        migrations.AlterField(
            model_name='experiencecertificate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencecertificate',
            name='experience_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencecertificate',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
