# Generated by Django 5.2.4 on 2025-07-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0033_alter_experiencecertificate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencecertificate',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
