# Generated by Django 5.2.4 on 2025-07-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0034_experiencecertificate_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencecertificate',
            name='gender',
        ),
    ]
