# Generated by Django 5.0.2 on 2025-08-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0036_jobcard_jobcardimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcardimage',
            name='jobcard',
        ),
        migrations.DeleteModel(
            name='JobCard',
        ),
        migrations.DeleteModel(
            name='JobCardImage',
        ),
    ]
