# Generated by Django 5.0.2 on 2025-09-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0037_remove_jobcardimage_jobcard_delete_jobcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='experience',
            field=models.TextField(blank=True, default=''),
        ),
    ]
