# Generated by Django 5.2.4 on 2026-02-06 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0001_initial'),
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='app2.jobrole'),
        ),
        migrations.AddField(
            model_name='servicelogcomplaint',
            name='assigned_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='app1.user'),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_service_logs', to='app1.user'),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='assigned_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_logs', to='app1.user'),
        ),
        migrations.AddField(
            model_name='serviceentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.user'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('name', 'district')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'day', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='leadhardwareprice',
            unique_together={('lead', 'hardware')},
        ),
        migrations.AlterUniqueTogether(
            name='documentcredential',
            unique_together={('document', 'credential')},
        ),
        migrations.AlterUniqueTogether(
            name='leadrequirementamount',
            unique_together={('lead', 'requirement')},
        ),
    ]
