# Generated by Django 5.1.1 on 2025-01-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobTitlee',
            new_name='JobTitle',
        ),
    ]
