# Generated by Django 5.1.1 on 2024-11-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='software_amounts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
