# Generated by Django 4.2.7 on 2025-11-11 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0001_initial'),
        ('software_master', '0001_initial'),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='app2.jobrole'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='app1.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.project'),
        ),
        migrations.AddField(
            model_name='servicelogcomplaint',
            name='assigned_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='app1.user'),
        ),
        migrations.AddField(
            model_name='servicelogcomplaint',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.complaint'),
        ),
        migrations.AddField(
            model_name='servicelogcomplaint',
            name='service_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.servicelog'),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_service_logs', to='app1.user'),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='assigned_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_logs', to='app1.user'),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='complaints',
            field=models.ManyToManyField(through='app1.ServiceLogComplaint', to='app1.complaint'),
        ),
        migrations.AddField(
            model_name='serviceentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='added_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.remindertype'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='responsible_persons',
            field=models.ManyToManyField(blank=True, related_name='reminders', to='app1.employee'),
        ),
        migrations.AddField(
            model_name='rating',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cv'),
        ),
        migrations.AddField(
            model_name='projectwork',
            name='members',
            field=models.ManyToManyField(related_name='project_works', to='app1.employee'),
        ),
        migrations.AddField(
            model_name='projectwork',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_works', to='app1.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.employee'),
        ),
        migrations.AddField(
            model_name='offerletterdetails',
            name='cv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter_details', to='app1.cv'),
        ),
        migrations.AddField(
            model_name='location',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='app1.area'),
        ),
        migrations.AddField(
            model_name='location',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='app1.district'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadrequirementamount',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_amounts', to='app1.lead'),
        ),
        migrations.AddField(
            model_name='leadrequirementamount',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.requirement'),
        ),
        migrations.AddField(
            model_name='leadhardwareprice',
            name='hardware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.hardware'),
        ),
        migrations.AddField(
            model_name='leadhardwareprice',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_prices', to='app1.lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='app1.area'),
        ),
        migrations.AddField(
            model_name='lead',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='app1.district'),
        ),
        migrations.AddField(
            model_name='lead',
            name='hardwares',
            field=models.ManyToManyField(blank=True, related_name='leads', to='app1.hardware'),
        ),
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='app1.location'),
        ),
        migrations.AddField(
            model_name='lead',
            name='requirements',
            field=models.ManyToManyField(to='app1.requirement'),
        ),
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
        migrations.AddField(
            model_name='laterequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employee'),
        ),
        migrations.AddField(
            model_name='laterequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.user'),
        ),
        migrations.AddField(
            model_name='earlyrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employee'),
        ),
        migrations.AddField(
            model_name='earlyrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentsettingfield',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app1.documentsetting'),
        ),
        migrations.AddField(
            model_name='documentsetting',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='app1.document'),
        ),
        migrations.AddField(
            model_name='documentcredential',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.credential'),
        ),
        migrations.AddField(
            model_name='documentcredential',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.officialdocument'),
        ),
        migrations.AddField(
            model_name='cv',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.agent'),
        ),
        migrations.AddField(
            model_name='cv',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cvs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cv',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.jobtitle'),
        ),
        migrations.AddField(
            model_name='complaintimage',
            name='complaint_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app1.servicelogcomplaint'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='software',
            field=models.ManyToManyField(blank=True, related_name='complaints', to='software_master.software'),
        ),
        migrations.AddField(
            model_name='breaktime',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employee'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app1.employee'),
        ),
        migrations.AddField(
            model_name='area',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='app1.district'),
        ),
        migrations.AlterUniqueTogether(
            name='leadrequirementamount',
            unique_together={('lead', 'requirement')},
        ),
        migrations.AlterUniqueTogether(
            name='leadhardwareprice',
            unique_together={('lead', 'hardware')},
        ),
        migrations.AlterUniqueTogether(
            name='documentcredential',
            unique_together={('document', 'credential')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'day', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('name', 'district')},
        ),
    ]
