# Generated by Django 5.1.1 on 2025-01-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobTitle',
        ),
    ]
