# Generated by Django 5.2.3 on 2025-11-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='organization',
            field=models.CharField(blank=True, choices=[('', 'Select Organization'), ('IMC', 'IMC'), ('SYSMAC', 'SYSMAC')], max_length=100, null=True),
        ),
    ]
