# Generated by Django 5.2.7 on 2026-05-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_initial'),
        ('purchase_order', '0003_alter_item_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments assigned to this user', related_name='users', to='purchase_order.department'),
        ),
    ]
