# Generated by Django 5.1.1 on 2025-01-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_jobtitlee_jobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
