# Generated by Django 5.1.1 on 2024-11-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_lead_software_amounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='software_amounts',
        ),
    ]
