# Generated by Django 5.1.1 on 2024-10-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
    ]
