# Generated by Django 5.1.1 on 2025-01-11 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_jobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.jobtitle'),
        ),
    ]
