# Generated by Django 5.1.1 on 2025-01-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_cv_address_alter_cv_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('admin', 'admin'), ('super_admin', 'super admin')], default='normal', max_length=20),
        ),
    ]
