# Generated by Django 5.1.1 on 2024-11-12 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_lead_software_amounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_amounts', to='app1.lead')),
            ],
            options={
                'unique_together': {('lead', 'software_name')},
            },
        ),
    ]
