# Generated by Django 5.1.1 on 2025-01-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_credential_officialdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcredential',
            name='additional_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
