# Generated by Django 5.1.1 on 2025-01-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_user_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('admin', 'Admin'), ('super_admin', 'Super Admin'), ('super_user', 'Super User'), ('user', 'User')], default='normal', max_length=20),
        ),
    ]
