# Generated by Django 5.1.1 on 2025-01-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_documentcredential_additional_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentcredential',
            unique_together={('document', 'credential')},
        ),
    ]
