# Generated by Django 5.1.1 on 2025-01-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_cv_job_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobTitle',
            new_name='JobTitlee',
        ),
    ]
