# Generated by Django 5.1.1 on 2025-01-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_documentcredential_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcredential',
            name='visibility',
            field=models.CharField(blank=True, choices=[('normal', 'Normal User'), ('admin_level', 'Admin Level User')], default='', max_length=20),
        ),
    ]
