# Generated by Django 5.1.1 on 2024-11-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_lead_software_amounts_delete_softwareamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='software_amounts',
        ),
    ]
