# Generated by Django 5.1.1 on 2025-01-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_documentcredential_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcredential',
            name='visibility',
        ),
    ]
