# Generated by Django 5.1.1 on 2025-01-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_user_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('normal', 'Normal User'), ('admin_level', 'Admin Level User')], default='normal', max_length=20),
        ),
    ]
