# Generated by Django 5.1.1 on 2025-01-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_documentcredential_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='visibility',
            field=models.CharField(blank=True, choices=[('normal', 'Normal User'), ('admin_level', 'Admin Level User')], help_text='Restrict visibility to a specific user level', max_length=20, null=True),
        ),
    ]
