# Generated by Django 5.1.1 on 2024-11-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
