# Generated by Django 5.1.1 on 2024-11-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_softwareamount_updated_at_alter_softwareamount_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='software',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
