# Generated by Django 5.1.1 on 2024-11-18 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_lead_software'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='software',
        ),
        migrations.DeleteModel(
            name='SoftwareAmount',
        ),
    ]
