# Generated by Django 5.1.1 on 2025-01-28 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_credential_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='credential',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='visibility',
            field=models.CharField(choices=[('all', 'All Users'), ('normal', 'Normal Users'), ('admin_level', 'Admin Level Users')], default='all', max_length=20),
        ),
    ]
