# Generated by Django 5.1.1 on 2024-11-02 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
