# Generated by Django 5.1.1 on 2025-01-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_credential_created_at_credential_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='visibility',
        ),
    ]
