# Generated by Django 5.1.1 on 2024-11-18 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_lead_software_delete_softwareamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadRequirementAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_amounts', to='app1.lead')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.requirement')),
            ],
            options={
                'unique_together': {('lead', 'requirement')},
            },
        ),
    ]
