# Generated by Django 5.1.1 on 2025-01-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_credential_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcredential',
            name='visible_to',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
