# Generated by Django 5.1.1 on 2024-11-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_leadrequirementamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='district',
            field=models.CharField(choices=[('', 'Select District'), ('alappuzha', 'Alappuzha'), ('ernakulam', 'Ernakulam'), ('idukki', 'Idukki'), ('kannur', 'Kannur'), ('kasaragod', 'Kasaragod'), ('kollam', 'Kollam'), ('kottayam', 'Kottayam'), ('kozhikode', 'Kozhikode'), ('malappuram', 'Malappuram'), ('palakkad', 'Palakkad'), ('pathanamthitta', 'Pathanamthitta'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('thrissur', 'Thrissur'), ('wayanad', 'Wayanad')], default='', max_length=50),
        ),
    ]
