# Generated by Django 5.1.1 on 2025-01-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_documentcredential_visible_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcredential',
            name='visible_to',
        ),
    ]
