# Generated by Django 5.1.1 on 2024-11-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_lead_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrequirementamount',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
