# Generated by Django 5.1.1 on 2025-01-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_documentcredential_visible_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='visibility',
            field=models.CharField(choices=[('normal', 'Normal User'), ('admin_level', 'Admin Level User')], default='normal', max_length=20),
        ),
    ]
