# Generated by Django 5.1.1 on 2024-11-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_lead_follow_up_required_lead_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
