# Generated by Django 5.1.1 on 2025-01-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_credential_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='visibility',
        ),
    ]
