# Generated by Django 5.1.1 on 2024-11-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_leadrequirementamount_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadrequirementamount',
            name='remarks',
        ),
    ]
