# Generated by Django 5.1.1 on 2025-01-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_credential_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='visibility',
            field=models.CharField(choices=[('normal', 'Normal User'), ('admin_level', 'Admin Level User')], default='normal', max_length=20),
        ),
    ]
