# Generated by Django 5.1.1 on 2024-11-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_leadrequirementamount_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='business_nature',
            field=models.CharField(choices=[('', 'Select'), ('supermarket', 'Supermarket'), ('textile', 'Textile'), ('restaurant', 'Restaurant'), ('retail', 'Retail'), ('wholesale', 'Wholesale'), ('footware', 'Footware'), ('production', 'production'), ('hardware', 'Hardware'), ('pharmacy', 'Pharmacy'), ('hospital', 'Hospital'), ('clinic', 'Clinic'), ('another', 'Another')], default='', max_length=100),
        ),
    ]
