# Generated by Django 5.1.1 on 2025-01-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_credential_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='credential',
            name='visibility',
            field=models.CharField(choices=[('all', 'All Users'), ('normal', 'Normal User'), ('admin_level', 'Admin Level User')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='credential',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
