# Generated by Django 5.1.1 on 2025-01-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_credential_description_credential_visibility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='description',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='visibility',
        ),
        migrations.AlterField(
            model_name='credential',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
