# Generated by Django 5.1.1 on 2024-11-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_lead_business_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='business_nature',
            field=models.CharField(choices=[('', 'Select'), ('supermarket', 'Supermarket'), ('textile', 'Textile'), ('restaurant', 'Restaurant'), ('Agency/Distribution', 'Agency/Distribution'), ('retail', 'Retail'), ('Auto Mobiles', 'Auto Mobiles'), ('Bakery', 'Bakery'), ('Boutique', 'Boutique'), ('Hyper Market', 'Hyper Market'), ('Lab', 'Lab'), ('Opticals', 'Opticals'), ('Pharmacy', 'Pharmacy'), ('School', 'School'), ('Hotels/ Resorts', 'Hotels/ Resorts'), ('wholesale', 'Wholesale'), ('footware', 'Footware'), ('Travels', 'Travels'), ('Jewellery', 'Jewellery'), ('production', 'production'), ('hardware', 'Hardware'), ('pharmacy', 'Pharmacy'), ('hospital', 'Hospital'), ('clinic', 'Clinic'), ('another', 'Another')], default='', max_length=100),
        ),
    ]
