# Generated by Django 5.1.1 on 2025-01-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_remove_credential_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='visibility',
            field=models.CharField(choices=[('all', 'All Users'), ('normal', 'Normal User'), ('admin_level', 'Admin Level User')], default='all', max_length=20),
        ),
    ]
