# Generated by Django 5.1.1 on 2025-01-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_credential_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('normal', 'Normal User'), ('admin_level', 'Admin Level User'), ('3level', '3 level'), ('4level', '4 level')], default='normal', max_length=20),
        ),
    ]
