# Generated by Django 5.1.1 on 2024-11-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_lead_business_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='planet_entry',
            field=models.BooleanField(default=False),
        ),
    ]
