# Generated by Django 5.1.1 on 2025-01-30 06:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_user_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='visibility',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('all', 'All Users'), ('normal', 'Normal User'), ('admin_level', 'Admin Level User'), ('3level', '3 Level User'), ('4level', '4 Level User')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
