# Generated by Django 5.1.1 on 2024-12-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_lead_business_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('normal', 'Normal User'), ('admin_level', 'Admin Level User')], default='normal', max_length=20),
        ),
    ]
