# Generated by Django 5.1.1 on 2025-01-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_credential_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='interview_status',
            field=models.BooleanField(default=False),
        ),
    ]
