# Generated by Django 5.1.1 on 2024-12-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_user_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='lead_voice_notes/'),
        ),
    ]
