# Generated by Django 5.1.1 on 2025-02-01 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_cv_interview_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge', models.IntegerField(default=0)),
                ('confidence', models.IntegerField(default=0)),
                ('attitude', models.IntegerField(default=0)),
                ('communication', models.IntegerField(default=0)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app1.cv')),
            ],
        ),
    ]
