# Generated by Django 5.1.1 on 2025-02-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_rating_appearance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='appearance',
        ),
    ]
