# Generated by Django 5.1.1 on 2025-02-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_remove_rating_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='appearance',
            field=models.IntegerField(default=0),
        ),
    ]
