# Generated by Django 5.1.1 on 2024-12-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
