# Generated by Django 5.1.1 on 2025-02-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_rating_expected_salary_rating_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='appearance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='attitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='communication',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='knowledge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
