# Generated by Django 5.1.1 on 2024-12-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='location',
            new_name='landmark',
        ),
    ]
