# Generated by Django 5.1.1 on 2024-12-16 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_rename_location_lead_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='app1.location'),
        ),
    ]
