# Generated by Django 5.1.1 on 2025-02-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_remove_rating_voice_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='voice_notes/'),
        ),
    ]
