# Generated by Django 5.1.1 on 2025-02-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_rating_voice_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
