# Generated by Django 5.1.1 on 2024-12-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_lead_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='district',
        ),
    ]
