# Generated by Django 5.1.1 on 2024-12-17 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_remove_lead_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='app1.area'),
        ),
        migrations.AddField(
            model_name='lead',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='app1.district'),
        ),
    ]
