# Generated by Django 5.1.1 on 2025-02-06 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_cv_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
