# Generated by Django 5.1.1 on 2025-02-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_cv_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
