# Generated by Django 5.1.1 on 2024-12-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_lead_area_lead_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='business_nature',
            field=models.CharField(choices=[('', 'Select'), ('agency_distribution', 'Agency/Distribution'), ('automobiles', 'Automobiles'), ('bakery', 'Bakery'), ('boutique', 'Boutique'), ('clinic', 'Clinic'), ('footwear', 'Footwear'), ('hardware', 'Hardware'), ('hospital', 'Hospital'), ('hotels_resorts', 'Hotels/Resorts'), ('hyper_market', 'Hyper Market'), ('jewellery', 'Jewellery'), ('lab', 'Lab'), ('opticals', 'Opticals'), ('pharmacy', 'Pharmacy'), ('production', 'Production'), ('restaurant', 'Restaurant'), ('retail', 'Retail'), ('school', 'School'), ('supermarket', 'Supermarket'), ('textile', 'Textile'), ('travels', 'Travels'), ('wholesale', 'Wholesale'), ('another', 'Another')], default='', max_length=100),
        ),
    ]
