# Generated by Django 5.1.1 on 2025-02-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_alter_cv_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='created_at',
        ),
    ]
