# Generated by Django 5.1.1 on 2024-12-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_alter_lead_business_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='business_nature',
            field=models.CharField(choices=[('', 'Select'), ('Agency/Distribution', 'Agency/Distribution'), ('Auto Mobiles', 'Auto Mobiles'), ('Bakery', 'Bakery'), ('Boutique', 'Boutique'), ('clinic', 'Clinic'), ('footware', 'Footware'), ('hardware', 'Hardware'), ('hospital', 'Hospital'), ('Hotels/ Resorts', 'Hotels/ Resorts'), ('Hyper Market', 'Hyper Market'), ('Jewellery', 'Jewellery'), ('Lab', 'Lab'), ('Opticals', 'Opticals'), ('Pharmacy', 'Pharmacy'), ('pharmacy', 'Pharmacy'), ('production', 'Production'), ('restaurant', 'Restaurant'), ('retail', 'Retail'), ('School', 'School'), ('supermarket', 'Supermarket'), ('textile', 'Textile'), ('Travels', 'Travels'), ('wholesale', 'Wholesale'), ('another', 'Another')], default='', max_length=100),
        ),
    ]
