# Generated by Django 5.1.1 on 2025-02-07 04:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_remove_cv_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
