# Generated by Django 5.1.1 on 2024-12-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_leadhardwareamount_lead_hardware'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='hardware',
        ),
        migrations.DeleteModel(
            name='LeadHardwareAmount',
        ),
    ]
