# Generated by Django 5.1.1 on 2024-12-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_remove_lead_hardware_delete_leadhardwareamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='hardware',
            field=models.ManyToManyField(blank=True, related_name='leads', to='app1.hardware'),
        ),
    ]
