# Generated by Django 5.1.1 on 2025-02-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_offerletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferLetter',
        ),
    ]
