# Generated by Django 5.1.1 on 2024-12-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_lead_hardware'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='hardware',
        ),
    ]
