# Generated by Django 5.1.1 on 2025-02-12 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_delete_offerletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter_details', to='app1.cv')),
            ],
        ),
    ]
