# Generated by Django 5.1.1 on 2025-02-15 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_offerletterdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='employees/')),
                ('phone_personal', models.CharField(max_length=15)),
                ('phone_residential', models.CharField(blank=True, max_length=15, null=True)),
                ('place', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='employee_attachments/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app1.employee')),
            ],
        ),
    ]
