# Generated by Django 5.1.1 on 2024-12-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_leadhardware'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadHardware',
        ),
    ]
