# Generated by Django 5.1.1 on 2024-12-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_delete_leadhardware'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='hardwares',
            field=models.ManyToManyField(blank=True, related_name='leads', to='app1.hardware'),
        ),
    ]
