# Generated by Django 5.1.1 on 2025-02-15 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_employee_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='designation',
            new_name='job_title',
        ),
    ]
