# Generated by Django 5.1.1 on 2025-02-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_rename_designation_employee_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
