# Generated by Django 5.1.1 on 2024-12-19 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_leadhardware'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leadhardware',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leadhardware',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadhardware',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_hardwares', to='app1.lead'),
        ),
        migrations.RemoveField(
            model_name='leadhardware',
            name='custom_price',
        ),
    ]
