# Generated by Django 5.1.1 on 2025-02-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_alter_employee_education_alter_employee_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
