# Generated by Django 5.1.1 on 2024-12-19 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_alter_leadhardware_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='hardware_prices',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='LeadHardwarePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.hardware')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.lead')),
            ],
            options={
                'unique_together': {('lead', 'hardware')},
            },
        ),
        migrations.DeleteModel(
            name='LeadHardware',
        ),
    ]
