# Generated by Django 5.1.1 on 2024-12-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_lead_hardware_prices_leadhardwareprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='hardware_prices',
        ),
        migrations.DeleteModel(
            name='LeadHardwarePrice',
        ),
    ]
