# Generated by Django 5.1.1 on 2025-02-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_experiencecertificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExperienceCertificate',
        ),
    ]
