# Generated by Django 5.1.1 on 2024-12-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_remove_lead_hardware_prices_delete_leadhardwareprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='business_nature',
            field=models.CharField(choices=[('', 'Select'), ('Agency/Distribution', 'Agency/Distribution'), ('Auto Mobiles', 'Auto Mobiles'), ('Bakery', 'Bakery'), ('Boutique', 'Boutique'), ('clinic', 'Clinic'), ('footware', 'Footware'), ('hardware', 'Hardware'), ('hospital', 'Hospital'), ('Hotels/ Resorts', 'Hotels/ Resorts'), ('Hyper Market', 'Hyper Market'), ('Jewellery', 'Jewellery'), ('Lab', 'Lab'), ('Opticals', 'Opticals'), ('Pharmacy', 'Pharmacy'), ('production', 'Production'), ('restaurant', 'Restaurant'), ('retail', 'Retail'), ('School', 'School'), ('supermarket', 'Supermarket'), ('textile', 'Textile'), ('Travels', 'Travels'), ('wholesale', 'Wholesale'), ('another', 'Another')], default='', max_length=100),
        ),
    ]
