# Generated by Django 5.1.1 on 2024-12-20 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0051_leadhardwareprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadhardwareprice',
            name='custom_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leadhardwareprice',
            name='hardware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.hardware'),
        ),
    ]
