# Generated by Django 5.1.1 on 2024-12-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_alter_leadhardwareprice_custom_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='added_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='added_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
