# Generated by Django 5.1.1 on 2025-02-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_documentsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentsetting',
            old_name='setting_name',
            new_name='name',
        ),
    ]
