# Generated by Django 5.1.1 on 2025-02-20 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_rename_setting_name_documentsetting_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsetting',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='document_attachments/'),
        ),
        migrations.AddField(
            model_name='documentsetting',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DocumentSettingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_value', models.TextField()),
                ('purpose', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='field_attachments/')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app1.documentsetting')),
            ],
        ),
    ]
