# Generated by Django 5.1.1 on 2025-01-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='created_at',
        ),
    ]
