# Generated by Django 5.1.1 on 2025-01-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0056_complaint_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('complaint', models.TextField()),
                ('remark', models.TextField()),
                ('voice_note', models.URLField(blank=True, null=True)),
                ('assigned_person', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
