# Generated by Django 5.1.1 on 2025-01-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0057_servicelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelog',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='voice_notes/'),
        ),
    ]
