# Generated by Django 5.1.1 on 2025-02-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0058_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
