# Generated by Django 5.1.1 on 2025-01-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0058_alter_servicelog_voice_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceLog',
        ),
    ]
