# Generated by Django 5.1.1 on 2025-02-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0059_cv_interview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
