# Generated by Django 5.1.1 on 2025-01-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0059_delete_servicelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('complaint', models.TextField()),
                ('remark', models.TextField()),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='voice_notes/')),
                ('assigned_person', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
