# Generated by Django 5.1.1 on 2025-01-04 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0060_servicelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelog',
            name='assigned_person',
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.complaint'),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
