# Generated by Django 5.1.1 on 2025-02-27 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0060_cv_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='selected',
        ),
    ]
