# Generated by Django 5.1.1 on 2025-02-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0061_remove_cv_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
