# Generated by Django 5.1.1 on 2025-01-04 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0061_remove_servicelog_assigned_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelog',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
    ]
