# Generated by Django 5.1.1 on 2025-01-04 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0062_servicelog_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelog',
            name='assigned_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_logs', to='app1.user'),
        ),
    ]
