# Generated by Django 5.1.1 on 2025-03-03 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0062_cv_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_cvs', to='app1.user'),
        ),
    ]
