# Generated by Django 5.1.1 on 2025-03-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0063_cv_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='added_by',
        ),
    ]
