# Generated by Django 5.1.1 on 2025-01-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0063_servicelog_assigned_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelog',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
