# Generated by Django 5.1.1 on 2025-03-03 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0064_remove_cv_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
    ]
