# Generated by Django 5.1.1 on 2025-01-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0064_servicelog_assigned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelog',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
