# Generated by Django 5.1.1 on 2025-01-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0065_alter_servicelog_assigned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelog',
            name='status',
            field=models.CharField(choices=[('not_completed', 'Not Completed'), ('completed', 'Completed')], default='not_completed', max_length=20),
        ),
    ]
