# Generated by Django 5.1.1 on 2025-01-08 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0066_servicelog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelog',
            name='status',
            field=models.CharField(choices=[('Not Completed', 'Not Completed'), ('Completed', 'Completed')], default='Not Completed', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.CharField(max_length=200)),
                ('complaint', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='New', max_length=50)),
                ('place', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
