# Generated by Django 5.1.1 on 2025-01-08 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0067_alter_servicelog_status_serviceentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceentry',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='New', max_length=20),
        ),
    ]
