# Generated by Django 5.1.1 on 2025-03-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0068_cv_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='created_by',
        ),
    ]
