# Generated by Django 5.1.1 on 2025-01-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0068_alter_serviceentry_options_alter_serviceentry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Solved', 'Solved')], default='Pending', max_length=20),
        ),
    ]
