# Generated by Django 5.1.1 on 2025-01-09 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0069_alter_serviceentry_date_alter_serviceentry_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceentry',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.complaint'),
        ),
    ]
