# Generated by Django 5.1.1 on 2025-01-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0070_alter_serviceentry_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceentry',
            name='complaint',
            field=models.TextField(),
        ),
    ]
