# Generated by Django 5.1.1 on 2025-03-04 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0070_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cvs', to='app1.user'),
        ),
    ]
