# Generated by Django 5.1.1 on 2025-01-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0071_alter_serviceentry_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
    ]
