# Generated by Django 5.1.1 on 2025-03-04 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0072_remove_cv_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.user'),
        ),
    ]
