# Generated by Django 5.1.1 on 2025-01-10 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0072_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.location'),
        ),
    ]
