# Generated by Django 5.1.1 on 2025-01-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0073_alter_agent_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
