# Generated by Django 5.1.1 on 2025-03-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0076_cv_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='created_by',
        ),
    ]
