# Generated by Django 5.1.1 on 2025-03-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0081_employeesalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_details', to='app1.employee'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
