# Generated by Django 5.1.1 on 2025-03-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0082_alter_employeesalary_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('normal', 'Normal User'), ('admin_level', 'Admin Level User'), ('3level', '3 level'), ('4level', '4 level'), ('5level', '5 level')], default='normal', max_length=20),
        ),
    ]
