# Generated by Django 5.1.1 on 2025-03-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0083_alter_user_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.CharField(blank=True, choices=[('', 'Select Organization'), ('IMC', 'IMC'), ('SYSMAC', 'SYSMAC')], max_length=10, null=True),
        ),
    ]
