# Generated by Django 5.1.1 on 2025-03-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0084_employee_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletterdetails',
            name='notice_period',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
