# Generated by Django 5.1.1 on 2025-03-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0085_offerletterdetails_notice_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerletterdetails',
            name='notice_period',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
