# Generated by Django 5.1.1 on 2025-03-15 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0088_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('status', models.CharField(choices=[('initial', 'Initial'), ('full', 'Full Day'), ('half', 'Half Day'), ('leave', 'Leave')], default='initial', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app1.employee')),
            ],
            options={
                'unique_together': {('employee', 'day', 'date')},
            },
        ),
    ]
