# Generated by Django 5.1.1 on 2025-03-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0089_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='punch_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
