# Generated by Django 5.1.1 on 2025-03-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0090_attendance_punch_in_attendance_punch_out'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsetting',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='documentsetting',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documentsetting',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='document_settings/'),
        ),
        migrations.AlterField(
            model_name='documentsetting',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
