# Generated by Django 5.1.1 on 2025-03-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0091_alter_documentsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsettingfield',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='documentsettingfield',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
