# Generated by Django 5.1.1 on 2025-03-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0093_remindertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
