# Generated by Django 5.1.1 on 2025-03-18 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0094_remove_employee_user_employee_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.user'),
        ),
    ]
