# Generated by Django 5.1.1 on 2025-03-19 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0095_remove_employee_user_name_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('no', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('remind_date', models.DateField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('reminder_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.remindertype')),
                ('responsible_persons', models.ManyToManyField(blank=True, related_name='reminders', to='app1.employee')),
            ],
        ),
    ]
