# Generated by Django 5.1.1 on 2025-03-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0097_attendance_punch_in_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='punch_in_latitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='punch_in_location',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='punch_in_longitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='punch_out_latitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='punch_out_location',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='punch_out_longitude',
        ),
    ]
