# Generated by Django 5.1.1 on 2025-03-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0110_remove_attendance_punch_in_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='punch_in_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_out_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
