# Generated by Django 5.1.1 on 2025-03-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0111_attendance_punch_in_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='punch_in_location',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='punch_out_location',
        ),
    ]
