# Generated by Django 5.1.1 on 2025-03-28 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0115_attendance_punch_in_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('initial', 'Not Marked'), ('full', 'Full Day'), ('half', 'Half Day'), ('leave', 'Leave')], default='initial', max_length=20),
        ),
    ]
