# Generated by Django 5.1.1 on 2025-03-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0116_alter_attendance_date_alter_attendance_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
