# Generated by Django 5.1.1 on 2025-04-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0119_leaverequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
