# Generated by Django 5.1.1 on 2025-04-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0122_alter_leaverequest_processed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='seen_by',
            field=models.ManyToManyField(related_name='seen_leave_requests', to='app1.user'),
        ),
    ]
