# Generated by Django 5.1.1 on 2025-04-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0123_leaverequest_seen_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='seen_by',
        ),
    ]
