# Generated by Django 5.1.1 on 2025-04-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0125_laterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='laterequest',
            name='delay_time',
            field=models.CharField(default='0 minutes', max_length=50),
        ),
    ]
