# Generated by Django 5.1.1 on 2025-04-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0126_laterequest_delay_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='laterequest',
            name='viewed_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laterequest',
            name='viewed_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='viewed_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='viewed_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
