# Generated by Django 5.1.1 on 2025-04-16 11:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0128_remove_laterequest_viewed_by_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('languages', models.CharField(max_length=200)),
                ('technologies', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('database_name', models.CharField(max_length=100)),
                ('domain_name', models.CharField(max_length=100)),
                ('domain_platform', models.CharField(max_length=100)),
                ('github_link', models.URLField()),
                ('client', models.CharField(default='', max_length=200)),
                ('project_status', models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Cancel', 'Cancel'), ('In Progress', 'In Progress'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('project_type', models.CharField(choices=[('Website', 'Website'), ('Web Application', 'Web Application'), ('Mobile Application', 'Mobile Application')], max_length=50)),
                ('project_duration', models.CharField(max_length=50)),
                ('assigned_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('deadline', models.DateField()),
                ('client', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('canceled', 'Canceled'), ('finished', 'Finished')], default='not_started', max_length=20)),
                ('members', models.ManyToManyField(related_name='project_works', to='app1.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_works', to='app1.project')),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
    ]
