# Generated by Django 5.1.1 on 2025-04-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0130_remove_project_description_project_notes_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_menus',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
