# Generated by Django 5.1.1 on 2025-04-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0131_user_allowed_menus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allowed_menus',
        ),
    ]
