# Generated by Django 5.1.1 on 2025-04-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0133_user_allowed_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allowed_menus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
