# Generated by Django 5.1.1 on 2025-04-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0134_alter_user_allowed_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allowed_menus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
