# Generated by Django 5.1.1 on 2025-04-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0135_alter_user_allowed_menus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allowed_menus',
        ),
    ]
