# Generated by Django 5.1.1 on 2025-04-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0136_remove_user_allowed_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_menus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
