# Generated by Django 5.0.2 on 2025-05-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0139_defaultsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Cancel', 'Cancel'), ('In Progress', 'In Progress'), ('Finish', 'Finish'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
