# Generated by Django 5.0.2 on 2025-05-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0140_alter_project_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Select Gender'), ('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
