# Generated by Django 5.0.2 on 2025-05-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0142_alter_cv_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceentry',
            name='mode_of_service',
            field=models.CharField(choices=[('Online', 'Online'), ('Onsite', 'Onsite')], default='Onsite', max_length=20),
        ),
    ]
