# Generated by Django 5.0.2 on 2025-05-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0143_serviceentry_mode_of_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceentry',
            name='service_type',
            field=models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software')], default='Software', max_length=20),
        ),
    ]
