# Generated by Django 5.0.2 on 2025-05-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0144_serviceentry_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
