# Generated by Django 5.0.2 on 2025-05-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0146_breaktime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breaktime',
            old_name='break_punch_in',
            new_name='break_end',
        ),
        migrations.RenameField(
            model_name='breaktime',
            old_name='break_punch_out',
            new_name='break_start',
        ),
        migrations.AddField(
            model_name='breaktime',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
