# Generated by Django 5.0.2 on 2025-05-13 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0147_rename_break_punch_in_breaktime_break_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breaktime',
            old_name='break_end',
            new_name='break_punch_in',
        ),
        migrations.RenameField(
            model_name='breaktime',
            old_name='break_start',
            new_name='break_punch_out',
        ),
        migrations.RemoveField(
            model_name='breaktime',
            name='duration',
        ),
    ]
