# Generated by Django 5.0.2 on 2025-05-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0148_rename_break_end_breaktime_break_punch_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaktime',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
