# Generated by Django 5.0.2 on 2025-05-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0151_project_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('both', 'Both')], default='software', max_length=10),
        ),
    ]
