# Generated by Django 5.0.2 on 2025-05-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0152_complaint_complaint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceentry',
            name='complaints',
            field=models.ManyToManyField(blank=True, to='app1.complaint'),
        ),
    ]
