# Generated by Django 5.0.2 on 2025-05-15 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0154_remove_serviceentry_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceentry',
            name='complaint',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
