# Generated by Django 5.0.2 on 2025-05-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0156_remove_serviceentry_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceentry',
            name='complaint',
            field=models.TextField(help_text='Comma-separated list of complaints'),
        ),
    ]
