# Generated by Django 5.0.2 on 2025-05-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0157_alter_serviceentry_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceentry',
            name='complaint',
            field=models.TextField(),
        ),
    ]
