# Generated by Django 5.0.2 on 2025-05-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0158_alter_serviceentry_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceentry',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
