# Generated by Django 5.0.2 on 2025-05-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0160_serviceentry_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceentry',
            name='companions',
            field=models.ManyToManyField(blank=True, related_name='service_companions', to='app1.user'),
        ),
    ]
