# Generated by Django 5.0.2 on 2025-05-16 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0161_serviceentry_companions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceentry',
            name='companions',
        ),
    ]
