# Generated by Django 5.0.2 on 2025-05-26 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0163_complaint_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='created_by',
        ),
    ]
