# Generated by Django 5.0.2 on 2025-05-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0166_alter_complaint_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
