# Generated by Django 5.0.2 on 2025-05-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0168_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='duty_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='duty_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
