# Generated by Django 5.0.2 on 2025-06-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0170_earlyrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EarlyRequest',
        ),
    ]
