# Generated by Django 5.0.2 on 2025-06-05 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0173_alter_earlyrequest_processed_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSalary',
        ),
    ]
