# Generated by Django 5.0.2 on 2025-06-12 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0174_delete_employeesalary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewTakenBy',
        ),
    ]
