# Generated by Django 5.0.2 on 2025-06-18 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0175_delete_interviewtakenby'),
        ('app2', '0024_jobrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='app2.jobrole'),
        ),
    ]
