# Generated by Django 5.0.2 on 2025-06-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0176_user_job_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceLog',
        ),
    ]
