# Generated by Django 5.0.2 on 2025-06-20 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0177_delete_servicelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('complaint_type', models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='service_log_voice_notes/')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_service_logs', to='app1.user')),
                ('assigned_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_logs', to='app1.user')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLogComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.complaint')),
                ('service_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.servicelog')),
            ],
        ),
        migrations.AddField(
            model_name='servicelog',
            name='complaints',
            field=models.ManyToManyField(through='app1.ServiceLogComplaint', to='app1.complaint'),
        ),
    ]
