# Generated by Django 5.0.2 on 2025-06-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0178_servicelog_servicelogcomplaint_servicelog_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelog',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
