# Generated by Django 5.0.2 on 2025-06-26 04:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0180_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelogcomplaint',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicelogcomplaint',
            name='assigned_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='app1.user'),
        ),
        migrations.AddField(
            model_name='servicelogcomplaint',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicelogcomplaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
