# Generated by Django 5.0.2 on 2025-06-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0182_servicelogcomplaint_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelogcomplaint',
            name='image',
        ),
    ]
