# Generated by Django 5.0.2 on 2025-06-30 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0184_complaintimage_servicelogcomplaint_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelogcomplaint',
            name='images',
        ),
    ]
