# Generated by Django 5.0.2 on 2025-06-30 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0185_remove_servicelogcomplaint_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplaintImage',
        ),
    ]
