# Generated by Django 5.0.2 on 2025-07-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0187_complaintimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelogcomplaint',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicelogcomplaint',
            name='started_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
