# Generated by Django 5.0.2 on 2025-09-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0189_lead_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('initial', 'Not Marked'), ('full', 'Full Day'), ('half', 'Half Day'), ('leave', 'Leave'), ('work_from_home', 'Work From Home')], default='initial', max_length=20),
        ),
    ]
