# Generated by Django 5.0.2 on 2025-10-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0190_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
