# Generated by Django 5.0.2 on 2025-10-16 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0191_leaverequest_note'),
        ('software_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='software_master.software'),
        ),
    ]
