# Generated by Django 5.0.2 on 2025-10-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0192_complaint_software'),
        ('software_master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='software',
        ),
        migrations.AddField(
            model_name='complaint',
            name='software',
            field=models.ManyToManyField(blank=True, related_name='complaints', to='software_master.software'),
        ),
    ]
