# Generated by Django 5.2.7 on 2026-06-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_new', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='company',
            field=models.CharField(choices=[('Sysmac Computers', 'Sysmac Computers'), ('Sysmac Info', 'Sysmac Info'), ('IMCB LLP', 'IMCB LLP')], max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
