# Generated by Django 5.2.7 on 2026-06-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_new', '0002_alter_collection_company_alter_collection_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=20),
        ),
    ]
