# Generated by Django 5.2.3 on 2025-12-18 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_initial'),
        ('software_update', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarecomplaint',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_complaints', to='app1.user'),
        ),
    ]
