# Generated by Django 5.2.3 on 2025-11-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelentry',
            name='purpose',
            field=models.CharField(blank=True, default='', help_text='Purpose of the trip', max_length=200),
        ),
    ]
