# Generated by Django 5.0.2 on 2025-10-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('two wheeler', 'Two wheeler'), ('four wheeler', 'Four wheeler')], max_length=20)),
                ('staff_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('odo_start', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odo_end', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip_from', models.CharField(max_length=100)),
                ('trip_to', models.CharField(max_length=100)),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='avg_mileage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average mileage in km/l', max_digits=6),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_copy',
            field=models.FileField(blank=True, null=True, upload_to='docs/ins/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='pollution_copy',
            field=models.FileField(blank=True, null=True, upload_to='docs/pol/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='rc_copy',
            field=models.FileField(blank=True, null=True, upload_to='docs/rc/'),
        ),
    ]
