# Generated by Django 5.2.3 on 2025-12-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelentry',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
