# Generated by Django 5.2.3 on 2025-10-20 04:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_management', '0002_vehicle_avg_mileage_alter_vehicle_insurance_copy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current fuel rate in rupees per liter', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], default='petrol', help_text='Type of fuel used by the vehicle', max_length=10),
        ),
    ]
