# Generated by Django 5.2.3 on 2025-10-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_management', '0002_fuelentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='avg_mileage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average mileage in km/l', max_digits=6),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_copy',
            field=models.FileField(blank=True, null=True, upload_to='docs/ins/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='pollution_copy',
            field=models.FileField(blank=True, null=True, upload_to='docs/pol/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='rc_copy',
            field=models.FileField(blank=True, null=True, upload_to='docs/rc/'),
        ),
    ]
