# Generated by Django 5.2.3 on 2025-10-24 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_management', '0003_vehicle_fuel_rate_vehicle_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='manufacture_year',
            field=models.PositiveIntegerField(default=2030, help_text='Year of manufacture', validators=[django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_number',
            field=models.CharField(default=2030, help_text='Model number of the vehicle', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_name',
            field=models.CharField(default=2030, help_text='Name of the vehicle', max_length=100),
            preserve_default=False,
        ),
    ]
