# Generated by Django 5.2.3 on 2025-10-13 08:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_management', '0003_vehicle_avg_mileage_alter_vehicle_insurance_copy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelentry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name_plural': 'Fuel Entries'},
        ),
        migrations.RemoveField(
            model_name='fuelentry',
            name='odo_end',
        ),
        migrations.RemoveField(
            model_name='fuelentry',
            name='odo_start',
        ),
        migrations.RemoveField(
            model_name='fuelentry',
            name='staff_name',
        ),
        migrations.RemoveField(
            model_name='fuelentry',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='fuel_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Fuel quantity filled in liters', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='odo_end_image',
            field=models.ImageField(blank=True, null=True, upload_to='odo_images/end/'),
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='odo_end_reading',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Odometer reading after the trip', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='odo_start_image',
            field=models.ImageField(blank=True, null=True, upload_to='odo_images/start/'),
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='odo_start_reading',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Odometer reading before the trip', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Link this fuel entry to a vehicle (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='fuel_management.vehicle'),
        ),
        migrations.AlterField(
            model_name='fuelentry',
            name='date',
            field=models.DateField(help_text='Date of the fuel entry'),
        ),
        migrations.AlterField(
            model_name='fuelentry',
            name='fuel_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost of the fuel', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='fuelentry',
            name='trip_from',
            field=models.CharField(blank=True, default='', help_text='Starting point of the trip', max_length=100),
        ),
        migrations.AlterField(
            model_name='fuelentry',
            name='trip_to',
            field=models.CharField(blank=True, default='', help_text='Destination point of the trip', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='avg_mileage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average mileage in km/l', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
