# Generated by Django 5.2.3 on 2025-10-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_management', '0004_alter_fuelentry_options_remove_fuelentry_odo_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
