# Generated by Django 5.2.3 on 2025-10-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_management', '0005_vehicle_end_time_vehicle_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='start_time',
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Trip end time', null=True),
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Trip start time', null=True),
        ),
    ]
