# Generated by Django 5.2.3 on 2025-10-17 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0191_leaverequest_note'),
        ('fuel_management', '0006_remove_vehicle_end_time_remove_vehicle_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelentry',
            name='travelled_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the trip', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.user'),
        ),
    ]
