# Generated by Django 5.2.3 on 2025-10-17 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_management', '0007_fuelentry_travelled_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelentry',
            name='date',
            field=models.DateField(help_text='Date of the trip'),
        ),
        migrations.AlterField(
            model_name='fuelentry',
            name='travelled_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuelentry',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Link this fuel entry to a vehicle', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='fuel_management.vehicle'),
        ),
    ]
